;;; svg-tag-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from svg-tag-mode.el

(autoload 'svg-tag-mode "svg-tag-mode" "\
Minor mode for graphical tag as rounded box.

This is a minor mode.  If called interactively, toggle the `Svg-Tag
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `svg-tag-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(put 'global-svg-tag-mode 'globalized-minor-mode t)
(defvar global-svg-tag-mode nil "\
Non-nil if Global Svg-Tag mode is enabled.
See the `global-svg-tag-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `global-svg-tag-mode'.")
(custom-autoload 'global-svg-tag-mode "svg-tag-mode" nil)
(autoload 'global-svg-tag-mode "svg-tag-mode" "\
Toggle Svg-Tag mode in all buffers.
With prefix ARG, enable Global Svg-Tag mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Svg-Tag mode is enabled in all buffers where `svg-tag-mode-on' would
do it.

See `svg-tag-mode' for more information on Svg-Tag mode.

(fn &optional ARG)" t)
(register-definition-prefixes "svg-tag-mode" '("svg-tag-"))

;;; End of scraped data

(provide 'svg-tag-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; svg-tag-mode-autoloads.el ends here
