;;; helm-flyspell-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-flyspell.el

(autoload 'helm-flyspell-correct "helm-flyspell" "\
Use helm for flyspell correction.
Adapted from `flyspell-correct-word-before-point'." t)
(register-definition-prefixes "helm-flyspell" '("helm-flyspell"))

;;; End of scraped data

(provide 'helm-flyspell-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-flyspell-autoloads.el ends here
