;;; cyphejor-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cyphejor.el

(defvar cyphejor-mode nil "\
Non-nil if Cyphejor mode is enabled.
See the `cyphejor-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `cyphejor-mode'.")
(custom-autoload 'cyphejor-mode "cyphejor" nil)
(autoload 'cyphejor-mode "cyphejor" "\
Toggle the `cyphejor-mode' minor mode.

With a prefix argument ARG, enable `cyphejor-mode' if ARG is
positive, and disable it otherwise.  If called from Lisp, enable
the mode if ARG is omitted or NIL, and toggle it if ARG is
`toggle'.

This global minor mode shortens names of major modes by using a
set of user-defined rules in `cyphejor-rules'.  See the
description of the variable for more information.

(fn &optional ARG)" t)
(register-definition-prefixes "cyphejor" '("cyphejor-"))

;;; End of scraped data

(provide 'cyphejor-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cyphejor-autoloads.el ends here
