;;; c-eldoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from c-eldoc.el

(autoload 'c-turn-on-eldoc-mode "c-eldoc" "\
Enable c-eldoc-mode." t)
(autoload 'c-eldoc-print-current-symbol-info "c-eldoc" "\
Return documentation string for the current symbol.")
(register-definition-prefixes "c-eldoc" '("c-eldoc-" "call-c-eldoc-cleanup"))

;;; End of scraped data

(provide 'c-eldoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; c-eldoc-autoloads.el ends here
