;;; resize-window-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from resize-window.el

(autoload 'resize-window "resize-window" "\
Resize the window.
Press n to enlarge down, p to enlarge up, b to enlarge left and f
to enlarge right." t)
(register-definition-prefixes "resize-window" '("resize-window-"))

;;; End of scraped data

(provide 'resize-window-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; resize-window-autoloads.el ends here
