;;; orgtbl-ascii-plot-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from orgtbl-ascii-plot.el

(autoload 'orgtbl-ascii-plot "orgtbl-ascii-plot" "\
Draws an ascii bars plot in a column, out of values found in another column.
  A numeric prefix may be given to override the default 12 characters wide plot.
    

(fn &optional ASK)" t)
(autoload 'orgtbl-ascii-plot-bindings "orgtbl-ascii-plot")
(if (functionp 'org-defkey) (orgtbl-ascii-plot-bindings) (setq org-load-hook (cons 'orgtbl-ascii-plot-bindings (if (boundp 'org-load-hook) org-load-hook))))
(register-definition-prefixes "orgtbl-ascii-plot" '("orgtbl-"))

;;; End of scraped data

(provide 'orgtbl-ascii-plot-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; orgtbl-ascii-plot-autoloads.el ends here
