;;; visual-regexp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from visual-regexp.el

(autoload 'vr/mc-mark "visual-regexp" "\
Convert regexp selection to multiple cursors.

(fn REGEXP START END)" t)
(autoload 'vr/replace "visual-regexp" "\
Regexp-replace with live visual feedback.

(fn REGEXP REPLACE START END)" t)
(autoload 'vr/query-replace "visual-regexp" "\
Use `vr/query-replace' like you would use `query-replace-regexp'.

(fn REGEXP REPLACE START END)" t)
(register-definition-prefixes "visual-regexp" '("vr--" "vr/"))

;;; End of scraped data

(provide 'visual-regexp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; visual-regexp-autoloads.el ends here
