;;; navi-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from navi-mode.el

(autoload 'navi-search-and-switch "navi-mode" "\
Call `occur' and immediatley switch to `*Navi:original-buffer-name*' buffer" t)
(register-definition-prefixes "navi-mode" '("navi"))

;;; End of scraped data

(provide 'navi-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; navi-mode-autoloads.el ends here
