;;; kaolin-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from kaolin-aurora-theme.el

(register-definition-prefixes "kaolin-aurora-theme" '("aurora"))


;;; Generated autoloads from kaolin-blossom-theme.el

(register-definition-prefixes "kaolin-blossom-theme" '("blossom" "kaolin-blossom-bg"))


;;; Generated autoloads from kaolin-breeze-theme.el

(register-definition-prefixes "kaolin-breeze-theme" '("breeze"))


;;; Generated autoloads from kaolin-bubblegum-theme.el

(register-definition-prefixes "kaolin-bubblegum-theme" '("bubblegum"))


;;; Generated autoloads from kaolin-dark-theme.el

(register-definition-prefixes "kaolin-dark-theme" '("dark"))


;;; Generated autoloads from kaolin-eclipse-theme.el

(register-definition-prefixes "kaolin-eclipse-theme" '("eclipse" "kaolin-eclipse-alt-bg"))


;;; Generated autoloads from kaolin-galaxy-theme.el

(register-definition-prefixes "kaolin-galaxy-theme" '("galaxy" "kaolin-galaxy-alt-bg"))


;;; Generated autoloads from kaolin-light-theme.el

(register-definition-prefixes "kaolin-light-theme" '("kaolin-light-alt-bg" "light"))


;;; Generated autoloads from kaolin-mono-dark-theme.el

(register-definition-prefixes "kaolin-mono-dark-theme" '("mono-dark"))


;;; Generated autoloads from kaolin-mono-light-theme.el

(register-definition-prefixes "kaolin-mono-light-theme" '("kaolin-mono-light-alt-bg" "mono-light"))


;;; Generated autoloads from kaolin-ocean-theme.el

(register-definition-prefixes "kaolin-ocean-theme" '("kaolin-ocean-alt-bg" "ocean"))


;;; Generated autoloads from kaolin-shiva-theme.el

(register-definition-prefixes "kaolin-shiva-theme" '("kaolin-shiva-" "shiva"))


;;; Generated autoloads from kaolin-temple-theme.el

(register-definition-prefixes "kaolin-temple-theme" '("temple"))


;;; Generated autoloads from kaolin-themes.el

(autoload 'kaolin-treemacs-theme "kaolin-themes" "\
Enable kaolin-themes treemacs theme with all-the-icons package.")
(when (and (boundp 'custom-theme-load-path) load-file-name) (let* ((base (file-name-directory load-file-name)) (dir (expand-file-name "themes/" base))) (add-to-list 'custom-theme-load-path (or (and (file-directory-p dir) dir) base))))
(register-definition-prefixes "kaolin-themes" '("define-kaolin-theme" "kaolin-theme"))


;;; Generated autoloads from kaolin-themes-lib.el

(register-definition-prefixes "kaolin-themes-lib" '("kaolin-"))


;;; Generated autoloads from kaolin-themes-treemacs.el

(register-definition-prefixes "kaolin-themes-treemacs" '("kaolin-t"))


;;; Generated autoloads from kaolin-valley-dark-theme.el

(register-definition-prefixes "kaolin-valley-dark-theme" '("kaolin-valley-dark-alt-" "valley-dark"))


;;; Generated autoloads from kaolin-valley-light-theme.el

(register-definition-prefixes "kaolin-valley-light-theme" '("kaolin-valley-light-alt-bg" "valley-light"))

;;; End of scraped data

(provide 'kaolin-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; kaolin-themes-autoloads.el ends here
