;;; popup-switcher-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from popup-switcher.el

(autoload 'psw-switch-buffer "popup-switcher" "\
Show buffers list menu to switch buffer.
If ARG show only buffers with files and without * in the beginning and end of
the buffer name.

(fn ARG)" t)
(autoload 'psw-switch-recentf "popup-switcher" nil t)
(autoload 'psw-switch-projectile-files "popup-switcher" nil t)
(autoload 'psw-switch-projectile-projects "popup-switcher" nil t)
(autoload 'psw-navigate-files "popup-switcher" "\


(fn &optional START-PATH)" t)
(autoload 'psw-switch-function "popup-switcher" nil t)
(register-definition-prefixes "popup-switcher" '("psw-"))

;;; End of scraped data

(provide 'popup-switcher-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; popup-switcher-autoloads.el ends here
