;;; lab-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lab-dark-theme.el

(register-definition-prefixes "lab-dark-theme" '("lab-dark"))


;;; Generated autoloads from lab-light-theme.el

(register-definition-prefixes "lab-light-theme" '("lab-light"))


;;; Generated autoloads from lab-themes.el

(add-to-list 'custom-theme-load-path (file-name-directory load-file-name))
(autoload 'lab-themes-load-style "lab-themes" "\
Load Lab theme variant STYLE.
Argument STYLE can be either 'light or 'dark.

(fn STYLE)" t)
(autoload 'lab-themes-switch-style "lab-themes" "\
Toggle between the light and dark style of Lab theme." t)
(register-definition-prefixes "lab-themes" '("lab-themes-current-style"))

;;; End of scraped data

(provide 'lab-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lab-themes-autoloads.el ends here
