;;; competitive-programming-snippets-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from competitive-programming-snippets.el

(autoload 'competitive-programming-snippets-init "competitive-programming-snippets" "\
Load the `competitive-programming-snippets' snippets directory.")
(register-definition-prefixes "competitive-programming-snippets" '("competitive-programming-snippets-dir"))

;;; End of scraped data

(provide 'competitive-programming-snippets-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; competitive-programming-snippets-autoloads.el ends here
