;;; one-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from one-dark-theme.el

(register-definition-prefixes "one-dark-theme" '("one-dark"))


;;; Generated autoloads from one-light-theme.el

(register-definition-prefixes "one-light-theme" '("one-light"))


;;; Generated autoloads from one-themes.el

(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "one-themes" '("emacs-one-" "one-themes-"))

;;; End of scraped data

(provide 'one-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; one-themes-autoloads.el ends here
