;;; helm-posframe-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-posframe.el

(autoload 'helm-posframe-enable "helm-posframe" "\
Enable helm-posframe." t)
(register-definition-prefixes "helm-posframe" '("helm-posframe-"))

;;; End of scraped data

(provide 'helm-posframe-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-posframe-autoloads.el ends here
