;;; modern-fringes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from modern-fringes.el

(autoload 'modern-fringes-invert-arrows "modern-fringes" "\
Apply ideal colors for the fringe truncation arrows in a flexible manner.
Should be used before (modern-fringes-mode) is enabled in the user's init file." t)
(defvar modern-fringes-mode nil "\
Non-nil if Modern-Fringes mode is enabled.
See the `modern-fringes-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `modern-fringes-mode'.")
(custom-autoload 'modern-fringes-mode "modern-fringes" nil)
(autoload 'modern-fringes-mode "modern-fringes" "\
Toggle Modern-Fringes mode on or off.

This is a global minor mode.  If called interactively, toggle the
`Modern-Fringes mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='modern-fringes-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "modern-fringes" '("modern-fringes-"))

;;; End of scraped data

(provide 'modern-fringes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; modern-fringes-autoloads.el ends here
