;;; helm-bm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-bm.el

(autoload 'helm-bm "helm-bm" "\
Show bookmarks of bm.el with `helm'.

Show bookmarks from all buffers or only `current-buffer' according to
`bm-cycle-all-buffers' value." t)
(register-definition-prefixes "helm-bm" '("helm-"))

;;; End of scraped data

(provide 'helm-bm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-bm-autoloads.el ends here
