;;; helm-purpose-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-purpose.el

(autoload 'helm-purpose-mini-ignore-purpose "helm-purpose" "\
Same as `helm-mini', but disable window-purpose while the command executes." t)
(autoload 'helm-purpose-switch-buffer-with-purpose "helm-purpose" "\
Switch to buffer, choose from buffers with purpose PURPOSE.
PURPOSE defaults to the purpose of the current buffer.

(fn &optional PURPOSE)" t)
(autoload 'helm-purpose-switch-buffer-with-some-purpose "helm-purpose" "\
Choose a purpose, then switch to a buffer with that purpose." t)
(autoload 'helm-purpose-setup "helm-purpose" "\
Setup Helm interface for Purpose.
Currently just sets `purpose-preferred-prompt' to 'helm.
Doesn't bind any keys.")
(register-definition-prefixes "helm-purpose" '("helm-"))

;;; End of scraped data

(provide 'helm-purpose-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-purpose-autoloads.el ends here
