;;; visual-regexp-steroids-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from visual-regexp-steroids.el

(autoload 'vr/select-replace "visual-regexp-steroids" nil t)
(autoload 'vr/select-query-replace "visual-regexp-steroids" nil t)
(autoload 'vr/select-mc-mark "visual-regexp-steroids" nil t)
(autoload 'vr/isearch-forward "visual-regexp-steroids" "\
Like isearch-forward, but using Python (or custom) regular expressions." t)
(autoload 'vr/isearch-backward "visual-regexp-steroids" "\
Like isearch-backward, but using Python (or custom) regular expressions." t)
(register-definition-prefixes "visual-regexp-steroids" '("vr--" "vr/"))

;;; End of scraped data

(provide 'visual-regexp-steroids-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; visual-regexp-steroids-autoloads.el ends here
