;;; tabbar-ruler-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from tabbar-ruler.el

(autoload 'tabbar-install-faces "tabbar-ruler" "\
Install faces for a FRAME.

(fn &optional FRAME)" t)
(autoload 'tabbar-ruler-up "tabbar-ruler" "\
Tabbar press up key.

(fn &optional ARG)" t)
(autoload 'tabbar-ruler-forward "tabbar-ruler" "\
Forward ruler. Takes into consideration if the home-key was pressed.
This is based on the variable `tabbar--buffer-show-groups'

(fn &optional ARG)" t)
(autoload 'tabbar-ruler-backward "tabbar-ruler" "\
Backward ruler.  Takes into consideration if the home-key was pressed.

(fn &optional ARG)" t)
(autoload 'tabbar-ruler-move "tabbar-ruler" "\
Start the movement for the tabbar" t)
(register-definition-prefixes "tabbar-ruler" '("after-modifying-buffer" "last-tabbar-ruler-tabbar-buffer-groups" "mode-icon-unknown" "on-" "tabbar-"))

;;; End of scraped data

(provide 'tabbar-ruler-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; tabbar-ruler-autoloads.el ends here
