;;; editorconfig-generate-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from editorconfig-generate.el

(autoload 'editorconfig-generate "editorconfig-generate" "\
Generate EditorConfig content for buffer BUF.
if BUF is omitted or nil, works for current buffer.

(fn &optional BUF)" t)
(register-definition-prefixes "editorconfig-generate" '("editorconfig-generate-"))

;;; End of scraped data

(provide 'editorconfig-generate-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; editorconfig-generate-autoloads.el ends here
