- name: Install Python Eggs
  pip: name={{item}} extra_args={{pip_extra_args|default('')}} state=latest
  with_items:
    - docutils                    # rst
    - flake8                      # python-flake8
    - pep8-naming
    - pylint                      # python-pylint
    - sphinx                      # rst-sphinx
    # For javascript-gjslint
    - http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz
  ignore_errors: True
