- name: Install Gems
  gem: name={{item}} user_install=no state=latest
       executable={{gem_executable|default('gem')}}
  with_items:
    - erubis                # eruby-erubis
    - foodcritic            # chef-foodcritic
    - haml                  # haml
    - puppet                # puppet-parser
    - puppet-lint           # puppet-lint
    - rubocop               # ruby-rubocop
    - ruby-lint             # ruby-rubylint
    - sass                  # sass
    - slim                  # slim
  ignore_errors: True
