- name: Download Scala
  get_url: url=http://downloads.typesafe.com/scala/{{scala_version}}/scala-{{scala_version}}.tgz
           dest=/usr/src/scala-{{scala_version}}.tar.gz
- name: Extract Scala
  unarchive: src=/usr/src/scala-{{scala_version}}.tar.gz copy=no dest=/opt/
             creates=/opt/scala-{{scala_version}}/bin/scalac
- name: Link Scala into PATH
  file: src=/opt/scala-{{scala_version}}/bin/scalac dest=/usr/local/bin/scalac
        state=link
- name: Download scalastyle
  get_url: url=https://oss.sonatype.org/content/repositories/releases/org/scalastyle/scalastyle-batch_2.10/{{scalastyle_version}}/scalastyle-batch_2.10-{{scalastyle_version}}-distribution.zip
           dest=/usr/src/scalastyle-batch_2.10-{{scalastyle_version}}-distribution.zip
- name: Extract scalastyle
  unarchive: src=/usr/src/scalastyle-batch_2.10-{{scalastyle_version}}-distribution.zip copy=no dest=/opt/
- name: Download JRuby
  get_url: url=http://jruby.org.s3.amazonaws.com/downloads/{{jruby_version}}/jruby-bin-{{jruby_version}}.tar.gz
           dest=/usr/src/jruby-{{jruby_version}}.tar.gz
- name: Extract JRuby
  unarchive: src=/usr/src/jruby-{{jruby_version}}.tar.gz copy=no dest=/opt/
             creates=/opt/jruby-{{jruby_version}}/bin/jruby
- name: Link JRuby into PATH
  file: src=/opt/jruby-{{jruby_version}}/bin/jruby dest=/usr/local/bin/jruby
        state=link
