- name: Install NPM packages
  npm: name={{item}} global=yes state=latest
  with_items:
    - coffee-script         # coffee
    - coffeelint            # coffee-coffeelint
    - csslint               # css-csslint
    - eslint                # javascript-eslint
    - handlebars            # handlebars
    - js-yaml               # yaml-jsyaml
    - jshint                # javascript-jshint
    - jsonlint              # json-jsonlint
    - less                  # less
  ignore_errors: True
