;;; git-messenger-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from git-messenger.el

(autoload 'git-messenger:popup-message "git-messenger" nil t)
(register-definition-prefixes "git-messenger" '("git-messenger"))

;;; End of scraped data

(provide 'git-messenger-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; git-messenger-autoloads.el ends here
