;;; org-seek-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-seek.el

(autoload 'org-seek-string "org-seek" "\
Full context searching STRING using ag in a given DIRECTORY.

By default STRING is the symbol under point unless called with a
prefix, prompts for flags to pass to ag.

(fn STRING DIRECTORY)" t)
(autoload 'org-seek-regexp "org-seek" "\
Full context searching REGEXP using ag in a given DIRECTORY.

By default REGEXP is the symbol under point unless called with a
prefix, prompts for flags to pass to ag.

(fn REGEXP DIRECTORY)" t)
(autoload 'org-seek-headlines "org-seek" "\
Search STRING in Org files headlines using ag in a given DIRECTORY.

By default STRING is the symbol under point unless called with a
prefix, prompts for flags to pass to ag.

(fn STRING DIRECTORY)" t)
(register-definition-prefixes "org-seek" '("org-seek-"))

;;; End of scraped data

(provide 'org-seek-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-seek-autoloads.el ends here
