;; danneskjold-theme.el --- beautiful high-contrast theme

;; Copyright (c) 2016-2025 Dmitry Akatov

;; Author: Dmitry Akatov <akatovda@google.com>
;; URL: https://github.com/rails-to-cosmos/danneskjold-theme
;; Package-Version: 20250302.1553
;; Package-Revision: 597cdf9135ce

;;; Commentary:

;;; Code:

(deftheme danneskjold "High-contrast minimalistic theme. Dark variant.")
(deftheme danneskjold-light "High-contrast minimalistic theme. Light variant.")

(defun danneskjold-toggle-theme ()
  "Toggle light danneskjold theme."
  (interactive)
  (if (custom-theme-enabled-p 'danneskjold-light)
      (progn
        (disable-theme 'danneskjold-light)
        (enable-theme 'danneskjold))
    (progn
      (disable-theme 'danneskjold)
      (enable-theme 'danneskjold-light))))

(defun danneskjold-invert-color (color)
  "Invert a hex color string."
  (let* ((hex-map '(("0" . 0) ("1" . 1) ("2" . 2) ("3" . 3) ("4" . 4)
                    ("5" . 5) ("6" . 6) ("7" . 7) ("8" . 8) ("9" . 9)
                    ("a" . 10) ("b" . 11) ("c" . 12) ("d" . 13) ("e" . 14) ("f" . 15)))
         (invert-component (lambda (component)
                             (format "%02x" (logxor #xFF (string-to-number component 16))))))
    (if (string-match "^#\\([a-fA-F0-9]\\{2\\}\\)\\([a-fA-F0-9]\\{2\\}\\)\\([a-fA-F0-9]\\{2\\}\\)$" color)
        (concat "#"
                (funcall invert-component (match-string 1 color))
                (funcall invert-component (match-string 2 color))
                (funcall invert-component (match-string 3 color)))
      (error "Invalid color format"))))

(let* ((class '((class color) (min-colors 89)))
       (background "#000000")
       (foreground "#FFFFFF")

       ;; doom-molokai-colors
       ;; https://github.com/hlissner/emacs-doom-theme/blob/master/doom-molokai-theme.el
       (black          "#000000")
       (white          "#FFFFFF")
       (yellow         "#ffcc00") ;; "#E2C770" "#F9BA32"
       (yellow-c       "#281580")

       (turquoise-bright "#1abc9c")
       (turquoise-dark "#16a085")
       (green-bright "#2ecc71")
       (green-dark "#27ae60")
       (blue-bright "#3498db")
       (blue-dark "#2980b9")
       (magenta-bright "#9b59b6")
       (magenta-dark "#8e44ad")
       (grey-blue-bright "#34495e")
       (grey-blue-dark "#2c3e50")
       (yellow-bright "#f1c40f")
       (yellow-dark "#f39c12")
       (orange-bright "#e67e22")
       (orange-dark "#d35400")
       (red-bright "#e74c3c")
       (red-dark "#c0392b")
       (grey-bright2 "#ecf0f1")
       (grey-bright1 "#bdc3c7")
       (grey-dark1 "#95a5a6")
       (grey-dark2 "#7f8c8d")
       (black "#000")

       (grey           "#C0C5CF")
       (grey-.5        "#828284")
       (grey-1         "#525254")
       (grey-2         "#39393D")
       (orange         "#ffa500") ;; "#FD971F"
       (red            "#E74C3C") ;; "#F34A4A"
       (magenta        "#F92672")
       (violet         "#7b68ee")
       (blue           "#4CB5F5") ;; "#268BD2"
       (blue+2         "#727280")
       (cyan           "#66D9EF")
       (green          "#B6E63E") ;; "#B3DE81"
       (green-3        "#86B20E")
       (dark-cyan      "#8FA1B3")

       ;; danneskjold-colors
       (frost        "#D0E1F9")
       (invisible    "#2b4b6e")
       (comment      "#A4C2EB")

       (sbt-midnight   "#282c34")
       (ada-midnight   "#21252b")
       (summer-flower  "#013220")
       (diredcl        "#749AF7")
       (dvi            "DarkViolet")
       (waddles        "#FF87BA")
       (krayola        "#E38B75")
       (red-forest     "#8b0000")

       (search-bg      green)
       (search-fg      black)
       (search-rest-bg violet)
       (search-rest-fg black)
       (highlight      orange)
       (current-line   "#1F1F1F")
       (selection      "#535556")
       (builtin        orange)
       (comments       grey-1)
       (constants      green)
       (delimiters     "#c0c5ce")
       (functions      cyan)
       (keywords       magenta)
       (methods        dark-cyan)
       (operators      violet)
       (type           cyan)
       (strings        green)
       (variables      orange)

       (error-highlight red)

       (active-minibuffer "#404046")

       (vc-modified    grey-2)
       (vc-added       green-3)
       (vc-deleted     red))

  (custom-theme-set-faces 'danneskjold
                          `(bmkp-D-mark ((,class (:foreground ,red))))
                          `(bmkp-local-directory ((,class (:foreground ,blue))))
                          `(bmkp-no-local ((,class (:foreground ,yellow :slant italic))))
                          `(bmkp-remote-file ((,class (:foreground ,green))))
                          `(bmkp-url ((,class (:foreground ,white))))
                          `(button ((,class (:foreground ,frost :underline t :weight normal))))
                          `(cider-stacktrace-error-class-face ((,class (:foreground ,yellow))))
                          `(cider-stacktrace-error-message-face ((,class (:foreground ,green))))
                          `(comint-highlight-input ((,class (:foreground ,foreground :bold t))))
                          `(comint-highlight-prompt ((,class (:foreground ,cyan))))
                          `(company-mouse ((,class (:background ,ada-midnight))))
                          `(company-preview ((,class (:background ,sbt-midnight))))
                          `(company-preview-common ((,class (:background ,sbt-midnight :foreground ,red))))
                          `(company-scrollbar-bg ((,class (:background ,sbt-midnight))))
                          `(company-scrollbar-fg ((,class (:background ,ada-midnight))))
                          `(company-tooltip ((,class (:foreground ,white :background ,ada-midnight))))
                          `(company-tooltip-common ((,class (:foreground ,yellow))))
                          `(company-tooltip-selection ((,class (:foreground ,white :background ,sbt-midnight))))
                          `(compilation-column-number ((,class (:foreground ,blue))))
                          `(compilation-error ((,class (:foreground ,red))))
                          `(compilation-info ((,class (:foreground ,diredcl))))
                          `(compilation-line-number ((,class (:foreground ,green))))
                          `(compilation-warning ((,class :foreground ,yellow)))
                          `(consult-file ((,class (:inherit consult-buffer))))
                          `(default ((,class (:foreground ,foreground :background ,black))))
                          `(diff-added ((,class (:foreground ,green-dark))))
                          `(diff-changed ((,class (:foreground ,magenta-bright))))
                          `(diff-file-header ((,class (:foreground ,blue-dark :background unspecified))))
                          `(diff-header ((,class (:foreground ,magenta-dark :background unspecified))))
                          `(diff-hl-change ((,class (:foreground ,blue-dark :background ,blue-dark))))
                          `(diff-hl-delete ((,class (:foreground ,orange-bright :background ,orange-dark))))
                          `(diff-hl-insert ((,class (:foreground ,green-dark :background ,green-dark))))
                          `(diff-hunk-header ((,class (:foreground ,magenta-bright))))
                          `(diff-refine-added ((,class (:inherit magit-diff-added-highlight :foreground ,blue-bright))))
                          `(diff-refine-removed ((,class (:inherit magit-diff-removed-highlight :foreground ,red-bright))))
                          `(diff-removed ((,class (:foreground ,yellow-dark))))
                          `(dired-collapsed-dirs ((,class (:background ,black :foreground ,frost))))
                          `(dired-directory ((,class (:foreground ,blue))))
                          `(dired-filetype-common ((,class (:foreground ,yellow))))
                          `(dired-filetype-execute ((,class (:foreground ,green))))
                          `(dired-filetype-link ((,class (:foreground ,blue :underline t))))
                          `(dired-filetype-omit ((,class (:foreground ,invisible))))
                          `(dired-filetype-plain ((,class (:foreground ,comment))))
                          `(dired-filetype-source ((,class (:foreground ,orange))))
                          `(dired-flagged ((,class (:foreground ,red :underline t))))
                          `(dired-git-face ((,class (:foreground ,red))))
                          `(dired-ignored ((,class (:foreground ,invisible))))
                          `(dired-marked ((,class (:foreground ,yellow :underline t))))
                          `(dired-rainbow-executable-unix-face ((,class (:foreground ,green))))
                          `(dired-subtree-depth-1-face ((,class (:background ,black))))
                          `(dired-subtree-depth-2-face ((,class (:background ,black))))
                          `(dired-subtree-depth-3-face ((,class (:background ,black))))
                          `(dired-subtree-depth-4-face ((,class (:background ,black))))
                          `(dired-subtree-depth-5-face ((,class (:background ,black))))
                          `(dired-subtree-depth-6-face ((,class (:background ,black))))
                          `(dired-subtree-depth-7-face ((,class (:background ,black))))
                          `(dired-subtree-depth-8-face ((,class (:background ,black))))
                          `(dired-subtree-depth-9-face ((,class (:background ,black))))
                          `(diredp-compressed-file-suffix ((,class (:foreground ,orange))))
                          ;; `(diredp-compressed-file-suffix ((,class (:foreground ,yellow-dark))))
                          `(diredp-date-time ((,class (:foreground ,diredcl))))
                          ;; `(diredp-date-time ((,class (:foreground ,yellow-bright))))
                          `(diredp-deletion ((,class (:foreground ,black :background ,red))))
                          ;; `(diredp-deletion ((,class (:foreground ,red-bright :weight bold :slant italic))))
                          `(diredp-deletion-file-name ((,class (:foreground ,black :background ,red))))
                          ;; `(diredp-deletion-file-name ((,class (:foreground ,red-bright :underline t))))
                          `(diredp-dir-heading ((,class (:foreground ,red-bright))))
                          `(diredp-dir-name ((,class (:foreground "DeepSkyBlue1"))))
                          `(diredp-dir-priv ((,class (:foreground ,blue))))
                          `(diredp-dir-priv ((,class (:foreground ,magenta-bright :background unspecified))))
                          `(diredp-exec-priv ((,class (:foreground ,green))))
                          ;; `(diredp-exec-priv ((,class (:foreground ,green-bright :background unspecified))))
                          `(diredp-executable-tag ((,class (:foreground ,green-bright :background unspecified))))
                          `(diredp-file-name ((,class (:foreground ,foreground))))
                          `(diredp-file-suffix ((,class (:foreground "coral"))))
                          `(diredp-flag-mark ((,class (:foreground ,black))))
                          ;; `(diredp-flag-mark ((,class (:foreground ,red-bright :weight bold))))
                          `(diredp-flag-mark-line ((,class (:foreground ,black :background ,yellow))))
                          ;; `(diredp-flag-mark-line ((,class (:inherit highlight))))
                          `(diredp-ignored-file-name ((,class ())))
                          ;; `(diredp-ignored-file-name ((,class (:foreground ,grey-dark1))))
                          `(diredp-link-priv ((,class (:background unspecified :foreground ,orange-bright))))
                          `(diredp-mode-line-flagged ((,class (:foreground ,red))))
                          ;; `(diredp-mode-line-flagged ((,class (:foreground ,yellow-dark))))
                          `(diredp-mode-line-marked ((,class (:foreground ,magenta-bright))))
                          ;; `(diredp-mode-line-marked ((,class (:foreground ,yellow))))
                          `(diredp-no-priv ((,class (:foreground ,grey-dark1 :background unspecified))))
                          ;; `(diredp-no-priv ((,class (:foreground ,white))))
                          `(diredp-number ((,class (:foreground ,yellow))))
                          ;; `(diredp-number ((,class (:foreground ,yellow-dark))))
                          `(diredp-other-priv ((,class (:background unspecified :foreground ,yellow-dark))))
                          `(diredp-rainbow-media-face ((,class (:foreground ,yellow))))
                          `(diredp-rare-priv ((,class (:foreground ,red-dark :background unspecified))))
                          ;; `(diredp-rare-priv ((,class (:foreground ,waddles))))
                          `(diredp-read-priv ((,class (:foreground ,blue-dark :background unspecified))))
                          ;; `(diredp-read-priv ((,class (:foreground ,red))))
                          `(diredp-symlink ((,class (:foreground ,orange-bright))))
                          ;; `(diredp-symlink ((,class (:foreground ,yellow))))
                          `(diredp-write-priv ((,class (:foreground ,magenta-bright :background unspecified))))
                          ;; `(diredp-write-priv ((,class (:foreground ,yellow))))
                          `(ediff-even-diff-A ((,class (:foreground unspecified :background unspecified :inverse-video t))))
                          `(ediff-even-diff-B ((,class (:foreground unspecified :background unspecified :inverse-video t))))
                          `(ediff-odd-diff-A  ((,class (:foreground ,grey-dark1 :background unspecified :inverse-video t))))
                          `(ediff-odd-diff-B  ((,class (:foreground ,grey-dark1 :background unspecified :inverse-video t))))
                          `(ein:cell-input-area ((,class (:background ,ada-midnight))))
                          `(ein:cell-input-prompt ((,class (:foreground ,yellow))))
                          `(ein:cell-output-area ((,class (:background ,black))))
                          `(ein:cell-output-prompt ((,class (:foreground ,orange))))
                          `(elfeed-search-date-face ((,class (:foreground ,diredcl))))
                          `(elfeed-search-feed-face ((,class (:foreground ,comment))))
                          `(elfeed-search-tag-face ((,class (:foreground ,green))))
                          `(elfeed-search-unread-title-face ((,class (:foreground ,white))))
                          `(epe-dir-face ((,class (:foreground ,blue))))
                          `(epe-remote-face ((,class (:foreground ,comment))))
                          `(epe-symbol-face ((,class (:foreground ,yellow))))
                          `(epresent-author-face ((,class (:inherit 'default))))
                          `(epresent-bullet-face ((,class (:inherit 'default))))
                          `(epresent-heading-face ((,class ())))
                          `(epresent-subheading-face ((,class ())))
                          `(epresent-title-face ((,class (:inherit 'default :height 2.0))))
                          `(erc-button ((,class (:foreground ,frost))))
                          `(erc-current-nick-face ((,class (:foreground ,red))))
                          `(erc-nick-default-face ((,class (:foreground ,frost))))
                          `(erc-notice-face ((,class (:foreground ,waddles))))
                          `(erc-prompt-face ((,class (:foreground ,green))))
                          `(erc-timestamp-face ((,class (:foreground ,red))))
                          `(eshell-ls-directory ((,class (:foreground ,blue))))
                          `(eshell-ls-executable ((,class (:foreground ,green))))
                          `(eshell-ls-missing ((,class (:foreground ,red))))
                          `(eshell-ls-product ((,class (:foreground ,comment))))
                          `(eshell-ls-readonly ((,class (:foreground ,invisible))))
                          `(eshell-ls-special ((,class (:foreground ,comment :underline t))))
                          `(eshell-ls-symlink ((,class (:foreground ,waddles))))
                          `(eshell-prompt ((,class (:foreground ,red))))
                          `(flx-highlight-face ((,class (:underline ,red :background ,sbt-midnight :foreground ,foreground))))
                          `(flycheck-warning ((,class (:underline (:color "orange" :style wave)))))
                          `(flymake-error ((,class (:underline (:color "red" :style wave)))))
                          `(font-lock-builtin-face ((,class (:foreground ,blue))))
                          `(font-lock-comment-delimiter-face ((,class (:foreground ,invisible))))
                          `(font-lock-comment-face ((,class (:foreground ,comment))))
                          `(font-lock-constant-face ((,class (:foreground ,yellow))))
                          `(font-lock-doc-face ((,class (:foreground ,green))))
                          `(font-lock-function-name-face ((,class (:foreground ,yellow))))
                          `(font-lock-keyword-face ((,class (:foreground ,frost))))
                          `(font-lock-string-face ((,class (:foreground ,green))))
                          `(font-lock-type-face ((,class (:foreground ,orange))))
                          `(font-lock-variable-name-face ((,class (:foreground ,foreground))))
                          `(font-lock-warning-face ((,class (:foreground ,yellow))))
                          `(fringe ((,class (:foreground ,invisible))))
                          `(hackernews-comment-count-face ((,class (:foreground ,red))))
                          `(hackernews-link-face ((,class (:foreground ,green))))
                          `(hackernews-score-face ((,class (:foreground ,white))))
                          `(header-line ((,class (:background ,black :foreground ,comment :underline ,comment :weight normal))))
                          `(hi-green-b ((,class (:foreground ,green))))
                          `(hi-red-b ((,class (:foreground ,red))))
                          `(hi-yellow ((,class (:foreground ,black :background ,yellow))))
                          `(hi-yellow-b ((,class (:foreground ,yellow))))
                          `(highlight ((,class (:background ,invisible :foreground ,black))))
                          `(highlight-quoted-symbol ((,class (:foreground ,waddles))))
                          `(highlight-symbol-face ((,class (:foreground ,black :background ,diredcl))))
                          `(hl-line ((,class (:background "keyboardFocusIndicatorColor"))))
                          `(hydra-face-blue ((,class (:foreground ,blue))))
                          `(hydra-face-red ((,class (:foreground ,red))))
                          `(ido-first-match ((,class (:bold t :foreground ,white))))
                          `(ido-only-match ((,class (:bold t :foreground ,white))))
                          `(ido-subdir ((,class (:foreground ,frost))))
                          `(ido-vertical-match-face ((,class (:underline ,diredcl))))
                          `(ido-virtual ((,class (:foreground ,comment))))
                          `(isearch ((,class (:foreground ,black :background ,invisible))))
                          `(ivy-action ((,class (:foreground ,yellow))))
                          `(ivy-confirm-face ((,class (:underline ,diredcl))))
                          `(ivy-current-match ((,class (:foreground "#FFCA00"))))
                          `(ivy-cursor ((,class (:foreground ,comment))))
                          `(ivy-highlight-face ((,class (:foreground ,orange))))
                          `(ivy-minibuffer-match-face-1 ((,class (:foreground ,white))))
                          `(ivy-minibuffer-match-face-2 ((,class (:underline ,red))))
                          `(ivy-minibuffer-match-face-3 ((,class (:underline ,orange))))
                          `(ivy-minibuffer-match-face-4 ((,class (:underline ,yellow))))
                          `(ivy-prompt-match ((,class (:bold t :foreground ,white))))
                          `(ivy-remote ((,class (:foreground ,white :slant italic))))
                          `(ivy-virtual ((,class (:foreground ,comment))))
                          `(jabber-chat-prompt-foreign ((,class (:foreground ,yellow))))
                          `(jabber-chat-prompt-local ((,class (:foreground ,frost))))
                          `(jabber-rare-time-face ((,class (:foreground ,sbt-midnight))))
                          `(jabber-roster-user-away ((,class (:foreground ,frost))))
                          `(jabber-roster-user-offline ((,class (:foreground ,comment))))
                          `(jabber-roster-user-online ((,class (:foreground ,green))))
                          `(jabber-roster-user-xa ((,class (:foreground ,yellow))))
                          `(jabber-title-large ((,class (:foreground ,yellow))))
                          `(jabber-title-medium ((,class (:foreground ,yellow))))
                          `(jabber-title-small ((,class (:foreground ,yellow))))
                          `(js2-function-param ((,class (:foreground ,yellow))))
                          `(jupyter-repl-traceback ((,class (:foreground ,orange))))
                          `(lazy-highlight ((,class (:foreground ,black :background ,yellow))))
                          `(ledger-font-xact-highlight-face ((,class (:background "#0e1824"))))
                          `(line-number ((,class (:foreground ,invisible))))
                          `(line-number-current-line ((,class (:foreground ,foreground))))
                          `(link ((,class (:foreground ,frost :underline t))))
                          `(linum ((,class (:foreground ,invisible))))
                          `(linum-highlight-face ((,class (:foreground ,foreground))))
                          `(lsp-face-highlight-read ((,class (:underline ,blue))))
                          `(magit-branch ((,class (:foreground ,green-dark))))
                          `(magit-branch-local ((,class (:foreground ,turquoise-bright))))
                          `(magit-branch-remote ((,class (:foreground ,yellow-bright))))
                          `(magit-diff-added ((,class (:foreground ,green-dark))))
                          `(magit-diff-added-highlight ((,class (:foreground ,green-bright :background "#0e1824"))))
                          `(magit-diff-context ((,class (:foreground ,grey-bright1))))
                          `(magit-diff-context-highlight ((,class (:foreground ,grey-bright2 :background "#0e1824"))))
                          `(magit-diff-file-heading ((,class (:foreground ,yellow))))
                          `(magit-diff-file-heading-highlight ((,class (:foreground ,yellow-bright :background "#0e1824"))))
                          `(magit-diff-hunk-heading ((,class (:foreground ,magenta-bright))))
                          `(magit-diff-hunk-heading-highlight ((,class (:inherit magit-diff-hunk-heading :weight bold))))
                          `(magit-diff-removed ((,class (:foreground ,red-dark))))
                          `(magit-diff-removed-highlight ((,class (:foreground ,red-bright :background "#0e1824"))))
                          `(magit-hash ((,class (:foreground ,grey-bright2))))
                          `(magit-header ((,class (:inherit unspecified :weight bold))))
                          `(magit-item-highlight ((,class (:inherit highlight :background unspecified))))
                          `(magit-log-graph ((,class (:foreground ,grey-dark2))))
                          `(magit-log-head-label-bisect-bad ((,class (:foreground ,red-dark))))
                          `(magit-log-head-label-bisect-good ((,class (:foreground ,green-dark))))
                          `(magit-log-head-label-default ((,class (:foreground ,yellow-bright :box unspecified :weight bold))))
                          `(magit-log-head-label-local ((,class (:foreground ,magenta-bright :box unspecified :weight bold))))
                          `(magit-log-head-label-remote ((,class (:foreground ,magenta-bright :box unspecified :weight bold))))
                          `(magit-log-head-label-tags ((,class (:foreground ,magenta-dark :box unspecified :weight bold))))
                          `(magit-log-sha1 ((,class (:foreground ,yellow-bright))))
                          `(magit-section ((,class (:inherit unspecified))))
                          `(magit-section-heading ((,class (:foreground ,blue-bright))))
                          `(magit-section-highlight ((,class (:background "#0e1824"))))
                          `(magit-section-title ((,class (:foreground ,blue-dark :weight bold))))
                          `(menu ((,class (:foreground ,foreground :background ,ada-midnight))))
                          `(message-header-name ((,class (:foreground ,comment))))
                          `(message-header-other ((,class (:foreground ,white))))
                          `(message-header-subject ((,class (:foreground ,white))))
                          `(message-header-to ((,class (:foreground ,white))))
                          `(minibuffer-prompt ((,class (:foreground ,diredcl))))
                          `(minimap-active-region-background ((,class (:background ,sbt-midnight))))
                          `(mmm-default-submode-face ((,class (:background ,ada-midnight))))
                          `(mode-line ((,class (:background ,black :foreground ,comment))))
                          `(mode-line-buffer-id ((,class (:foreground ,foreground))))
                          `(mode-line-inactive ((,class (:background ,black :foreground ,invisible))))
                          `(monky-diff-add ((,class (:foreground ,green))))
                          `(monky-diff-del ((,class (:foreground ,red))))
                          `(org-agenda-calendar-event ((,class (:foreground ,yellow :slant italic))))
                          `(org-agenda-clocking ((,class (:foreground ,diredcl :background ,ada-midnight))))
                          `(org-agenda-current-time ((,class (:foreground ,frost))))
                          `(org-agenda-date ((,class (:foreground ,blue))))
                          `(org-agenda-date-today ((,class (:foreground ,white))))
                          `(org-agenda-date-weekend ((,class (:foreground ,white :bold t))))
                          `(org-agenda-diary ((,class (:foreground ,orange :slant italic))))
                          `(org-agenda-dimmed-todo-face ((,class (:foreground ,comment))))
                          `(org-agenda-done ((,class (:foreground ,green))))
                          `(org-agenda-structure ((,class (:foreground ,white))))
                          `(org-archived                 ((,class (:foreground ,invisible))))
                          `(org-block                    ((,class (:background "#0e1824"))))
                          `(org-block-begin-line         ((,class (:foreground "selectedControlColor" :slant italic))))
                          `(org-block-end-line           ((,class (:inherit org-block-begin-line))))
                          `(org-checkbox-statistics-done ((,class (:inherit org-done))))
                          `(org-checkbox-statistics-todo ((,class (:inherit org-todo))))
                          `(org-code                     ((,class (:foreground ,orange))))
                          `(org-column                   ((,class (:background ,black))))
                          `(org-column-title             ((,class (:background ,black :foreground ,comment))))
                          `(org-date                     ((,class (:foreground "LightSteelBlue2" :underline "LightSteelBlue4"))))
                          `(org-document-info            ((,class (:foreground ,foreground))))
                          `(org-document-info-keyword    ((,class (:foreground ,frost :bold t))))
                          `(org-document-title           ((,class (:foreground ,foreground :bold t))))
                          `(org-done                     ((,class (:foreground ,green))))
                          `(org-drawer                   ((,class (:foreground ,orange))))
                          `(org-ellipsis                 ((,class (:inherit hs-face :underline unspecified))))
                          `(org-footnote                 ((,class (:foreground ,orange))))
                          `(org-formula                  ((,class (:foreground ,orange))))
                          `(org-habit-alert-face ((,class (:background ,black :underline t :foreground ,yellow))))
                          `(org-habit-alert-future-face ((,class (:background ,black :underline t :foreground ,yellow))))
                          `(org-habit-clear-face ((,class (:background ,black :foreground ,frost :underline t))))
                          `(org-habit-clear-future-face ((,class (:background ,black :underline t :foreground ,frost))))
                          `(org-habit-overdue-face ((,class (:background ,black :underline t :foreground ,red))))
                          `(org-habit-overdue-future-face ((,class (:background ,black :underline t :foreground ,red))))
                          `(org-habit-ready-face ((,class (:background ,black :foreground ,green :underline t))))
                          `(org-habit-ready-future-face ((,class (:background ,black :underline t :foreground ,green))))
                          `(org-headline-done ((,class (:foreground ,comment))))
                          `(org-hide                     ((,class (:foreground ,black))))
                          `(org-latex-and-related        ((,class (:foreground "#FAF9FF"))))
                          `(org-level-1                  ((,class (:foreground ,foreground))))
                          `(org-level-2                  ((,class (:foreground ,foreground))))
                          `(org-level-3                  ((,class (:foreground ,foreground))))
                          `(org-level-4                  ((,class (:foreground ,foreground))))
                          `(org-level-5                  ((,class (:foreground ,foreground))))
                          `(org-level-6                  ((,class (:foreground ,foreground))))
                          `(org-level-7                  ((,class (:foreground ,foreground))))
                          `(org-level-8                  ((,class (:foreground ,foreground))))
                          `(org-link                     ((,class (:foreground ,frost :underline ,invisible))))
                          `(org-list-dt                  ((,class (:foreground ,yellow))))
                          `(org-meta-line                ((,class (:foreground ,frost))))
                          `(org-mode-line-clock ((,class (:foreground ,yellow))))
                          `(org-mode-line-clock-overrun ((,class (:foreground ,red))))
                          `(org-priority                 ((,class (:foreground ,foreground))))
                          `(org-property-value          ((,class (:foreground ,foreground))))
                          `(org-quote                    ((,class (:slant italic :foreground ,foreground))))
                          `(org-scheduled ((,class (:foreground ,foreground))))
                          `(org-scheduled-previously ((,class (:foreground ,violet :slant italic))))
                          `(org-scheduled-today ((,class (:foreground ,white))))
                          `(org-special-keyword          ((,class (:foreground "#ffcc00"))))
                          `(org-table                    ((,class (:foreground ,yellow))))
                          `(org-tag                      ((,class (:foreground ,frost :slant italic))))
                          `(org-time-grid ((,class (:foreground ,invisible))))
                          `(org-todo                     ((,class (:foreground ,yellow))))
                          `(org-upcoming-deadline ((,class (:foreground ,orange))))
                          `(org-upcoming-distant-deadline ((,class (:foreground ,comment))))
                          `(org-warning ((,class (:foreground "#FFCA00"))))
                          `(package-name                 ((,class (:inherit org-link))))
                          `(perspeen-selected-face ((,class (:foreground ,frost))))
                          `(popup-face ((,class (:foreground ,foreground :background ,ada-midnight))))
                          `(popup-menu-mouse-face ((,class (:foreground ,foreground :background ,sbt-midnight))))
                          `(popup-menu-selection-face ((,class (:foreground ,foreground :background ,sbt-midnight))))
                          `(popup-tip-face ((,class (:foreground ,black :background ,yellow))))
                          `(powerline-active1 ((,class (:foreground ,yellow))))
                          `(powerline-active2 ((,class (:foreground ,comment))))
                          `(powerline-inactive1 ((,class (:foreground ,comment))))
                          `(powerline-inactive2 ((,class (:foreground ,comment))))
                          `(prodigy-green-face ((,class (:foreground ,green))))
                          `(prodigy-red-face ((,class (:foreground ,red))))
                          `(prodigy-yellow-face ((,class (:foreground ,yellow))))
                          `(rainbow-delimiters-depth-1-face ((,class (:foreground ,green))))
                          `(rainbow-delimiters-depth-10-face ((,class (:foreground ,yellow))))
                          `(rainbow-delimiters-depth-2-face ((,class (:foreground ,red))))
                          `(rainbow-delimiters-depth-3-face ((,class (:foreground ,frost))))
                          `(rainbow-delimiters-depth-4-face ((,class (:foreground ,yellow))))
                          `(rainbow-delimiters-depth-5-face ((,class (:foreground ,waddles))))
                          `(rainbow-delimiters-depth-6-face ((,class (:foreground ,frost))))
                          `(rainbow-delimiters-depth-7-face ((,class (:foreground ,green))))
                          `(rainbow-delimiters-depth-8-face ((,class (:foreground ,red))))
                          `(rainbow-delimiters-depth-9-face ((,class (:foreground ,frost))))
                          `(region ((,class (:background "#373d4f"))))
                          `(secondary-selection ((,class ())))
                          `(shadow ((,class (:foreground ,comment))))
                          `(show-paren-match ((,class (:background ,blue :foreground ,foreground))))
                          `(shr-link ((,class (:foreground ,frost :underline t))))
                          `(sqlplus-table-even-rows-face ((,class (:foreground ,white :background ,ada-midnight))))
                          `(sqlplus-table-head-face ((,class (:foreground ,yellow))))
                          `(sqlplus-table-odd-rows-face ((,class (:foreground ,white))))
                          `(swiper-match-face-1 ((,class (:foreground ,white))))
                          `(swiper-match-face-2 ((,class (:underline ,red))))
                          `(swiper-match-face-3 ((,class (:underline ,orange))))
                          `(swiper-match-face-4 ((,class (:underline ,yellow))))
                          `(vc-annotate-face-3F3FFF ((,class (:foreground ,blue))))
                          `(vc-annotate-face-3FF3FF ((,class (:foreground ,frost))))
                          `(vc-annotate-face-3FFF56 ((,class (:foreground ,violet))))
                          `(vc-annotate-face-56FF3F ((,class (:foreground ,green))))
                          `(vc-annotate-face-FF3F3F ((,class (:foreground ,red))))
                          `(vc-annotate-face-FFF33F ((,class (:foreground ,yellow))))
                          `(vertical-border ((,class (:foreground "#223959"))))
                          `(vertico-current ((,class (:foreground "#FFCA00"))))
                          `(icomplete-selected-match ((,class (:foreground "#FFCA00"))))
                          `(wgrep-done-face                  ((,class (:foreground ,green))))
                          `(wgrep-face                  ((,class (:foreground ,yellow))))
                          `(wgrep-file-face                  ((,class (:background ,(danneskjold-invert-color yellow-c) :foreground ,yellow))))
                          `(wgrep-reject-face                  ((,class (:foreground ,red))))
                          `(whitespace-empty ((,class (:foreground ,ada-midnight))))
                          `(whitespace-hspace ((,class (:foreground ,ada-midnight))))
                          `(whitespace-indentation ((,class (:foreground ,ada-midnight))))
                          `(whitespace-line ((,class ())))
                          `(whitespace-newline ((,class (:foreground ,ada-midnight))))
                          `(whitespace-space ((,class (:foreground ,ada-midnight))))
                          `(whitespace-space-after-tab ((,class (:foreground ,ada-midnight))))
                          `(whitespace-tab ((,class (:foreground ,ada-midnight))))
                          `(widget-button ((,class (:foreground ,yellow))))
                          `(widget-field ((,class (:foreground ,white :background ,sbt-midnight))))
                          `(yas-field-highlight-face ((,class (:background ,ada-midnight)))))

  (custom-theme-set-faces 'danneskjold-light
                          '(org-block ((t (:extend t :background "ghost white"))))
                          '(org-upcoming-deadline ((t (:foreground "purple3"))))
                          `(company-tooltip-selection ((t (:background "#ffd600"))))
                          `(diredp-compressed-file-suffix ((t (:foreground "#f39c12"))))
                          `(diredp-compressed-file-suffix ((t (:foreground "#ffa500"))))
                          `(diredp-date-time ((t (:foreground "#749AF7"))))
                          `(diredp-date-time ((t (:foreground "goldenrod1"))))
                          `(diredp-deletion ((t (:foreground "#e74c3c" :weight bold :slant italic))))
                          `(diredp-deletion-file-name ((t (:foreground "#e74c3c" :underline t))))
                          `(diredp-dir-heading ((t (:foreground "#e74c3c"))))
                          `(diredp-dir-name ((t (:foreground "blue"))))
                          `(diredp-dir-priv ((t (:foreground "#9b59b6" :background unspecified))))
                          `(diredp-exec-priv ((t (:foreground "#2ecc71" :background unspecified))))
                          `(diredp-executable-tag ((t (:foreground "#2ecc71" :background unspecified))))
                          `(diredp-file-name ((t (:foreground "black"))))
                          `(diredp-file-suffix ((t (:foreground "coral"))))
                          `(diredp-flag-mark ((t (:foreground "#e74c3c" :weight bold))))
                          `(diredp-flag-mark-line ((t (:inherit highlight))))
                          `(diredp-ignored-file-name ((t ())))
                          `(diredp-ignored-file-name ((t (:foreground "#95a5a6"))))
                          `(diredp-link-priv ((t (:background unspecified :foreground "#e67e22"))))
                          `(diredp-mode-line-flagged ((t (:foreground "#f39c12"))))
                          `(diredp-mode-line-marked ((t (:foreground "#9b59b6"))))
                          `(diredp-no-priv ((t (:foreground "#95a5a6" :background unspecified))))
                          `(diredp-number ((t (:foreground "#f39c12"))))
                          `(diredp-number ((t (:foreground "#ffcc00"))))
                          `(diredp-other-priv ((t (:background unspecified :foreground "#f39c12"))))
                          `(diredp-rainbow-media-face ((t (:foreground "#ffcc00"))))
                          `(diredp-rare-priv ((t (:foreground "#c0392b" :background unspecified))))
                          `(diredp-read-priv ((t (:foreground "#2980b9" :background unspecified))))
                          `(diredp-symlink ((t (:foreground "#e67e22"))))
                          `(diredp-symlink ((t (:foreground "#ffcc00"))))
                          `(diredp-write-priv ((t (:foreground "#9b59b6" :background unspecified))))
                          `(font-lock-comment-face ((t (:foreground "#7f8c8d"))))
                          `(highlight ((t (:background "honeydew" :extend t))))
                          `(hl-line ((t (:background "gray98"))))
                          `(ivy-current-match ((t (:weight bold :background "#ffd600"))))
                          `(ivy-minibuffer-match-face-1 ((t (:foreground "black"))))
                          `(line-number ((t (:foreground "grey"))))
                          `(line-number-current-line ((t (:foreground "#749AF7"))))
                          `(mode-line-buffer-read-only-face ((t (:foreground "brown4"))))
                          `(org-agenda-current-time ((t (:foreground "black" :weight bold)))))
                          `(org-block-begin-line ((t (:foreground "black" :weight bold :background "white"))))
                          `(org-block-end-line ((t (:foreground "black" :weight bold :background "white"))))
                          `(org-ellipsis ((t (:underline unspecified))))
                          `(org-meta-line ((t (:foreground "#9b59b6"))))
                          `(org-verbatim ((t (:background "gray96" :box (:line-width 2 :color "gray96")))))
                          `(swiper-match-face-1 ((t (:foreground "black"))))
                          `(tooltip ((t (:foreground "black" :background "white")))))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'danneskjold)
;;; danneskjold-theme.el ends here
