;;; dts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dts-mode.el

(autoload 'dts-mode "dts-mode" "\
Major mode for editing Devicetrees

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.dts\\'" . dts-mode))
(add-to-list 'auto-mode-alist '("\\.dtsi\\'" . dts-mode))
(register-definition-prefixes "dts-mode" '("dts-"))

;;; End of scraped data

(provide 'dts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dts-mode-autoloads.el ends here
