;;; counsel-tramp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from counsel-tramp.el

(autoload 'counsel-tramp "counsel-tramp" "\
Open your ~/.ssh/config with counsel interface.
You can connect your server with tramp" t)
(register-definition-prefixes "counsel-tramp" '("counsel-tramp-"))

;;; End of scraped data

(provide 'counsel-tramp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; counsel-tramp-autoloads.el ends here
