;;; leuven-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from leuven-dark-theme.el

(autoload 'leuven-dark-scale-font "leuven-dark-theme" "\
Function for splicing optional font heights into face descriptions.
CONTROL can be a number, nil, or t.  When t, use DEFAULT-HEIGHT.

(fn CONTROL DEFAULT-HEIGHT)")
(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "leuven-dark-theme" '("leuven-dark"))


;;; Generated autoloads from leuven-theme.el

(autoload 'leuven-scale-font "leuven-theme" "\
Function for splicing optional font heights into face descriptions.
CONTROL can be a number, nil, or t.  When t, use DEFAULT-HEIGHT.

(fn CONTROL DEFAULT-HEIGHT)")
(when (and (boundp 'custom-theme-load-path) load-file-name) (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "leuven-theme" '("leuven"))

;;; End of scraped data

(provide 'leuven-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; leuven-theme-autoloads.el ends here
