;;; helm-hunks-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-hunks.el

(autoload 'helm-hunks "helm-hunks" "\
Helm-hunks entry point." t)
(autoload 'helm-hunks-current-buffer "helm-hunks" "\
Helm-hunks entry point current buffer." t)
(autoload 'helm-hunks-staged "helm-hunks" "\
Helm-hunks entry point staged hunks." t)
(autoload 'helm-hunks-staged-current-buffer "helm-hunks" "\
Helm-hunks entry point staged hunks current buffer." t)
(register-definition-prefixes "helm-hunks" '("helm-hunks-"))

;;; End of scraped data

(provide 'helm-hunks-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-hunks-autoloads.el ends here
