;;; helm-ctest-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-ctest.el

(autoload 'helm-ctest "helm-ctest" nil t)
(register-definition-prefixes "helm-ctest" '("helm-ctest-"))

;;; End of scraped data

(provide 'helm-ctest-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-ctest-autoloads.el ends here
