;;; dired-k-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from dired-k.el

(autoload 'dired-k-no-revert "dired-k" "\
Same as `dired-k' except not calling `revert-buffer'." t)
(autoload 'dired-k "dired-k" "\
Highlighting dired buffer by file size, last modified time, and git status.
This is inspired by `k' zsh script" t)
(register-definition-prefixes "dired-k" '("dired-k-"))


;;; Generated autoloads from direx-k.el

(autoload 'direx-k "direx-k" nil t)
(register-definition-prefixes "direx-k" '("direx-k--"))

;;; End of scraped data

(provide 'dired-k-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; dired-k-autoloads.el ends here
