;;; use-package-chords-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from use-package-chords.el

(defalias 'use-package-autoloads/:chords 'use-package-autoloads-mode)
(defalias 'use-package-normalize/:chords 'use-package-normalize-binder)
(autoload 'use-package-handler/:chords "use-package-chords" "\
Handler for `:chords' keyword in `use-package'.

(fn NAME KEYWORD ARG REST STATE)")

;;; End of scraped data

(provide 'use-package-chords-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; use-package-chords-autoloads.el ends here
