;;; cquery-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cquery.el

(register-definition-prefixes "cquery" '("cquery-"))


;;; Generated autoloads from cquery-call-hierarchy.el

(register-definition-prefixes "cquery-call-hierarchy" '("cquery-call-hierarchy"))


;;; Generated autoloads from cquery-code-lens.el

(register-definition-prefixes "cquery-code-lens" '("cquery-"))


;;; Generated autoloads from cquery-common.el

(register-definition-prefixes "cquery-common" '("cquery--"))


;;; Generated autoloads from cquery-inheritance-hierarchy.el

(register-definition-prefixes "cquery-inheritance-hierarchy" '("cquery-inheritance-hierarchy"))


;;; Generated autoloads from cquery-semantic-highlighting.el

(register-definition-prefixes "cquery-semantic-highlighting" '("cquery-"))


;;; Generated autoloads from cquery-tree.el

(register-definition-prefixes "cquery-tree" '("cquery-tree-"))

;;; End of scraped data

(provide 'cquery-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cquery-autoloads.el ends here
