;;; company-tabnine-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-tabnine.el

(autoload 'company-tabnine "company-tabnine" "\
`company-mode' backend for TabNine.

See documentation of `company-backends' for details.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-tabnine" '("company-tabnine-"))

;;; End of scraped data

(provide 'company-tabnine-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-tabnine-autoloads.el ends here
