- name: Download DMD
  get_url: url=http://downloads.dlang.org/releases/2014/dmd_{{dmd.version}}.0-0_amd64.deb
           dest=/usr/src/dmd_{{dmd.version}}.0-0_amd64.deb
- name: Install DMD
  apt: deb=/usr/src/dmd_{{dmd.version}}.0-0_amd64.deb state=installed
