- name: Install Cabal
  apt: name='cabal-install-{{cabal_version}}' state=latest install_recommends=false
  tags:
    - cabal
- name: Set default Cabal
  alternatives: name=cabal link=/usr/local/bin/cabal
                path=/opt/cabal/{{cabal_version}}/bin/cabal
  tags:
    - cabal
# Update the package list, if it doesn't exist, or is older than a week (i.e.
# 604800 seconds)
- name: Check Cabal package list
  stat: path=/root/.cabal/packages/hackage.haskell.org/00-index.tar.gz
  register: cabal_package_list
- name: Check current time
  command: date '+%s'
  register: current_time
  when: cabal_package_list.stat.exists
- name: Update Cabal package list
  command: sudo cabal update
  when: "not cabal_package_list.stat.exists or \
        (current_time.stdout.strip()|float|default(0) - cabal_package_list.stat.mtime) > 604800"
