- name: Add Haskell PPA
  apt_repository: repo='ppa:hvr/ghc' state=present
- name: Install GHC
  apt: name='ghc-{{ghc_version}}' state=latest install_recommends=false
- name: Set default GHC
  alternatives: name={{item}} link=/usr/local/bin/{{item}}
                path=/opt/ghc/{{ghc_version}}/bin/{{item}}
  with_items:
    - ghc
    - ghc-pkg
    - ghci
    - haddock
    - hp2ps
    - hpc
    - hsc2hs
    - runghc
    - runhaskell
- include: cabal.yml
  tags: cabal
