;;; ample-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ample-flat-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(autoload 'ample-flat-theme "ample-flat-theme" "\
Apply the ample-flat-theme." t)
(register-definition-prefixes "ample-flat-theme" '("ample-flat"))


;;; Generated autoloads from ample-light-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(autoload 'ample-light-theme "ample-light-theme" "\
Apply the ample-light-theme." t)
(register-definition-prefixes "ample-light-theme" '("ample-light"))


;;; Generated autoloads from ample-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(autoload 'ample-theme "ample-theme" "\
Apply the ample-theme." t)
(register-definition-prefixes "ample-theme" '("ample"))

;;; End of scraped data

(provide 'ample-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ample-theme-autoloads.el ends here
