;;; ng2-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ng2-html.el

(autoload 'ng2-html-mode "ng2-html" "\
Major mode for Angular 2 templates

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.component.html\\'" . ng2-html-mode))
(register-definition-prefixes "ng2-html" '("ng2-html-"))


;;; Generated autoloads from ng2-mode.el

(autoload 'ng2-mode "ng2-mode" "\
Activates the appropriate Angular 2-related mode for the buffer." t)


;;; Generated autoloads from ng2-shared.el

(register-definition-prefixes "ng2-shared" '("ng2-"))


;;; Generated autoloads from ng2-ts.el

(autoload 'ng2-ts-mode "ng2-ts" "\
Major mode for Angular 2 TypeScript

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.component.ts\\'" . ng2-ts-mode))
(add-to-list 'auto-mode-alist '("\\.service.ts\\'" . ng2-ts-mode))
(add-to-list 'auto-mode-alist '("\\.pipe.ts\\'" . ng2-ts-mode))
(add-to-list 'auto-mode-alist '("\\.directive.ts\\'" . ng2-ts-mode))
(add-to-list 'auto-mode-alist '("\\.guard.ts\\'" . ng2-ts-mode))
(add-to-list 'auto-mode-alist '("\\.module.ts\\'" . ng2-ts-mode))
(register-definition-prefixes "ng2-ts" '("ng2-ts-"))

;;; End of scraped data

(provide 'ng2-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ng2-mode-autoloads.el ends here
