;;; numpydoc-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from numpydoc.el

(autoload 'numpydoc-use-yasnippet "numpydoc" "\
Enable yasnippet insertion (see `numpydoc-insertion-style')." t)
(autoload 'numpydoc-use-prompt "numpydoc" "\
Enable minibuffer prompt insertion (see `numpydoc-insertion-style')." t)
(autoload 'numpydoc-use-templates "numpydoc" "\
Enable template text insertion (see `numpydoc-insertion-style')." t)
(autoload 'numpydoc-generate "numpydoc" "\
Generate NumPy style docstring for Python function.
Assumes that the current location of the cursor is somewhere in the
function that is being documented." t)
(register-definition-prefixes "numpydoc" '("numpydoc-"))

;;; End of scraped data

(provide 'numpydoc-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; numpydoc-autoloads.el ends here
