;;; elscreen-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from elscreen.el

(autoload 'elscreen-start "elscreen" nil t)
(register-definition-prefixes "elscreen" '("elscreen-"))


;;; Generated autoloads from elscreen-buffer-list.el

(register-definition-prefixes "elscreen-buffer-list" '("buffer-dead-p" "elscreen-" "reorder-buffer-list" "toggle-elscreen-buffer-list"))


;;; Generated autoloads from elscreen-color-theme.el

(register-definition-prefixes "elscreen-color-theme" '("elscreen-color-theme-"))


;;; Generated autoloads from elscreen-dired.el

(register-definition-prefixes "elscreen-dired" '("elscreen-dired-version"))


;;; Generated autoloads from elscreen-dnd.el

(register-definition-prefixes "elscreen-dnd" '("elscreen-dnd-"))


;;; Generated autoloads from elscreen-gf.el

(register-definition-prefixes "elscreen-gf" '("elscreen-gf-"))


;;; Generated autoloads from elscreen-goby.el

(register-definition-prefixes "elscreen-goby" '("elscreen-goby-version"))


;;; Generated autoloads from elscreen-howm.el

(register-definition-prefixes "elscreen-howm" '("elscreen-howm-" "howm-save-and-kill-buffer/screen"))


;;; Generated autoloads from elscreen-server.el

(register-definition-prefixes "elscreen-server" '("elscreen-server-"))


;;; Generated autoloads from elscreen-speedbar.el

(register-definition-prefixes "elscreen-speedbar" '("elscreen-speedbar-"))


;;; Generated autoloads from elscreen-w3m.el

(register-definition-prefixes "elscreen-w3m" '("elscreen-w3m-"))


;;; Generated autoloads from elscreen-wl.el

(register-definition-prefixes "elscreen-wl" '("elscreen-wl-"))

;;; End of scraped data

(provide 'elscreen-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; elscreen-autoloads.el ends here
