;;; smeargle-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from smeargle.el

(autoload 'smeargle-clear "smeargle" "\
Clear smeargle overlays in current buffer." t)
(autoload 'smeargle "smeargle" "\
Highlight regions by last updated time.

(fn &optional UPDATE-TYPE)" t)
(autoload 'smeargle-commits "smeargle" "\
Highlight regions by age of commits." t)
(register-definition-prefixes "smeargle" '("smeargle-"))

;;; End of scraped data

(provide 'smeargle-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; smeargle-autoloads.el ends here
