;;; immaterial-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from immaterial-dark-theme.el

(register-definition-prefixes "immaterial-dark-theme" '("immaterial-dark"))


;;; Generated autoloads from immaterial-light-theme.el

(register-definition-prefixes "immaterial-light-theme" '("immaterial-light"))


;;; Generated autoloads from immaterial-theme.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "immaterial-theme" '("immaterial-"))

;;; End of scraped data

(provide 'immaterial-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; immaterial-theme-autoloads.el ends here
