;;; helm-gitignore-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-gitignore.el

(autoload 'helm-gitignore "helm-gitignore" "\
Helm to generate .gitignore using gitignore.io." t)
(register-definition-prefixes "helm-gitignore" '("helm-gitignore--"))

;;; End of scraped data

(provide 'helm-gitignore-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-gitignore-autoloads.el ends here
