- name: Download elixir
  get_url: url=https://github.com/elixir-lang/elixir/releases/download/v{{version}}/Precompiled.zip
           dest=/usr/src/elixir-{{version}}.zip
- name: Create Elixir directory
  file: path=/opt/elixir-{{version}} state=directory
        owner=root group=root mode=0755
- name: Extract Elixir
  unarchive: src=/usr/src/elixir-{{version}}.zip copy=no
             dest=/opt/elixir-{{version}}
             creates=/opt/elixir-{{version}}/bin/elixirc
- name: Put Elixir compiler in PATH
  file: path=/usr/local/bin/elixirc state=link
        src=/opt/elixir-{{version}}/bin/elixirc
