;;; oauth2-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from oauth2.el

(autoload 'oauth2-refresh-access "oauth2" "\
Refresh OAuth access TOKEN.
TOKEN should be obtained with `oauth2-request-access'.  HOST-NAME is
optional but highly recommended which is required for the cache to work.

(fn TOKEN &optional HOST-NAME)")
(autoload 'oauth2-auth "oauth2" "\
Authenticate application via OAuth2 at AUTH-URL.
TOKEN-URL is the URL for making the request.  CLIENT-ID and
CLIENT-SECRET are provided by the service provider.  SCOPE identifies
the resources that your application can access on the user's behalf.
STATE is a string that your application uses to maintain the state
between the request and redirect response.  REDIRECT-URI is used when
requesting access-token.  The default value for desktop application is
usually \"urn:ietf:wg:oauth:2.0:oob\".  USER-NAME is the login user name
and is required to provide a unique plstore id for users on the same
service provider.  HOST-NAME is the server to request access, e.g. IMAP
or SMTP server address.  Its value should match the one when calling
`oauth2-auth-and-store'.  Leaving HOST-NAME as nil effectively disables
caching and will request a new token on each request.  CODE-VERIFIER is
used for the PKCE extension and is required when it was already provided
during authorization.

Returns an `oauth2-token'.

(fn AUTH-URL TOKEN-URL CLIENT-ID CLIENT-SECRET &optional SCOPE STATE REDIRECT-URI USER-NAME HOST-NAME CODE-VERIFIER)")
(autoload 'oauth2-auth-and-store "oauth2" "\
Request access to a resource and store it.
AUTH-URL and TOKEN-URL are provided by the service provider.  CLIENT-ID
and CLIENT-SECRET should be generated by the service provider when a
user registers an application.  SCOPE identifies the resources that your
application can access on the user's behalf.  STATE is a string that
your application uses to maintain the state between the request and
redirect response.  USER-NAME is the login user name and is required to
provide a unique plstore id for users on the same service provider.
HOST-NAME is the server to request authentication, e.g. IMAP or SMTP
server address.  Leaving HOST-NAME as nil effectively disables caching
and will request a new token on each refresh.  USE-PKCE controls whether
to enable the PKCE extension of RFC7636 which is supported by most
OAuth2 providers and recommended.

Returns an `oauth2-token'.

(fn AUTH-URL TOKEN-URL SCOPE CLIENT-ID CLIENT-SECRET &optional REDIRECT-URI STATE USER-NAME HOST-NAME USE-PKCE)")
(register-definition-prefixes "oauth2" '("oauth2-"))

;;; End of scraped data

(provide 'oauth2-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; oauth2-autoloads.el ends here
