;;; p4-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from p4.el

(register-definition-prefixes "p4" '("add" "annotate" "branches" "changes" "clients" "diff" "edit" "flush" "fstat" "have" "jobs" "labels" "opened" "p4-" "print" "reconcile" "refresh" "reopen" "resolve" "revert" "status" "sync" "tickets" "unlock" "update" "where"))

;;; End of scraped data

(provide 'p4-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; p4-autoloads.el ends here
