language: emacs-lisp
env:
  - EMACS=emacs24
  - EMACS=emacs-snapshot
before_install:
  - sudo add-apt-repository -y ppa:rquillo/ansible
  - sudo apt-get update -y -q
  - sudo apt-get install -y ansible
  - ansible-playbook -v playbooks/travis.yml
  - export PATH="/opt/ghc/7.8.3/bin:${GOPATH}/bin:${HOME}/.local/bin:${HOME}/.cabal/bin:$PATH"
install:
  # Install our packages
  - make EMACS=$EMACS deps
script:
  # Run unit tests.
  - make EMACS=$EMACS compile
  - make EMACS=$EMACS test
