language: emacs-lisp
env:
  - EMACS=emacs24
  # Flycheck must compile cleanly on latest Emacs
  - EMACS=emacs-snapshot EMACSFLAGS="--eval '(setq byte-compile-error-on-warn t)'"
before_install:
  # Provision the test environment, and setup a proper PATH
  - sudo add-apt-repository -y ppa:rquillo/ansible
  - sudo apt-get update -y -q
  - sudo apt-get install -y ansible
  - ansible-playbook -v playbooks/travis.yml
  - export PATH="/opt/ghc/7.8.3/bin:${GOPATH}/bin:${HOME}/.local/bin:${HOME}/.cabal/bin:$PATH"
install:
  # Install our packages
  - make EMACS=$EMACS deps
script:
  # Byte-compile the file
  - make EMACS=$EMACS EMACSFLAGS="${EMACSFLAGS}" compile
  # Run the unit tests
  - make EMACS=$EMACS test
