;;; airline-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from airline-alduin-theme.el

(register-definition-prefixes "airline-alduin-theme" '("airline-alduin"))


;;; Generated autoloads from airline-angr-theme.el

(register-definition-prefixes "airline-angr-theme" '("airline-angr"))


;;; Generated autoloads from airline-apprentice-theme.el

(register-definition-prefixes "airline-apprentice-theme" '("airline-apprentice"))


;;; Generated autoloads from airline-atomic-theme.el

(register-definition-prefixes "airline-atomic-theme" '("airline-atomic"))


;;; Generated autoloads from airline-ayu_dark-theme.el

(register-definition-prefixes "airline-ayu_dark-theme" '("airline-ayu_dark"))


;;; Generated autoloads from airline-ayu_light-theme.el

(register-definition-prefixes "airline-ayu_light-theme" '("airline-ayu_light"))


;;; Generated autoloads from airline-ayu_mirage-theme.el

(register-definition-prefixes "airline-ayu_mirage-theme" '("airline-ayu_mirage"))


;;; Generated autoloads from airline-badwolf-theme.el

(register-definition-prefixes "airline-badwolf-theme" '("airline-badwolf"))


;;; Generated autoloads from airline-base16-gui-dark-theme.el

(register-definition-prefixes "airline-base16-gui-dark-theme" '("airline-base16-gui-dark"))


;;; Generated autoloads from airline-base16-gui-light-theme.el

(register-definition-prefixes "airline-base16-gui-light-theme" '("airline-base16-gui-light"))


;;; Generated autoloads from airline-base16-shell-dark-theme.el

(register-definition-prefixes "airline-base16-shell-dark-theme" '("airline-base16-shell-dark"))


;;; Generated autoloads from airline-base16-theme.el

(register-definition-prefixes "airline-base16-theme" '("airline-base16"))


;;; Generated autoloads from airline-base16_3024-theme.el

(register-definition-prefixes "airline-base16_3024-theme" '("airline-base16_3024"))


;;; Generated autoloads from airline-base16_adwaita-theme.el

(register-definition-prefixes "airline-base16_adwaita-theme" '("airline-base16_adwaita"))


;;; Generated autoloads from airline-base16_apathy-theme.el

(register-definition-prefixes "airline-base16_apathy-theme" '("airline-base16_apathy"))


;;; Generated autoloads from airline-base16_ashes-theme.el

(register-definition-prefixes "airline-base16_ashes-theme" '("airline-base16_ashes"))


;;; Generated autoloads from airline-base16_atelier_cave-theme.el

(register-definition-prefixes "airline-base16_atelier_cave-theme" '("airline-base16_atelier_cave"))


;;; Generated autoloads from airline-base16_atelier_cave_light-theme.el

(register-definition-prefixes "airline-base16_atelier_cave_light-theme" '("airline-base16_atelier_cave_light"))


;;; Generated autoloads from airline-base16_atelier_dune-theme.el

(register-definition-prefixes "airline-base16_atelier_dune-theme" '("airline-base16_atelier_dune"))


;;; Generated autoloads from airline-base16_atelier_dune_light-theme.el

(register-definition-prefixes "airline-base16_atelier_dune_light-theme" '("airline-base16_atelier_dune_light"))


;;; Generated autoloads from airline-base16_atelier_estuary-theme.el

(register-definition-prefixes "airline-base16_atelier_estuary-theme" '("airline-base16_atelier_estuary"))


;;; Generated autoloads from airline-base16_atelier_estuary_light-theme.el

(register-definition-prefixes "airline-base16_atelier_estuary_light-theme" '("airline-base16_atelier_estuary_light"))


;;; Generated autoloads from airline-base16_atelier_forest-theme.el

(register-definition-prefixes "airline-base16_atelier_forest-theme" '("airline-base16_atelier_forest"))


;;; Generated autoloads from airline-base16_atelier_forest_light-theme.el

(register-definition-prefixes "airline-base16_atelier_forest_light-theme" '("airline-base16_atelier_forest_light"))


;;; Generated autoloads from airline-base16_atelier_heath-theme.el

(register-definition-prefixes "airline-base16_atelier_heath-theme" '("airline-base16_atelier_heath"))


;;; Generated autoloads from airline-base16_atelier_heath_light-theme.el

(register-definition-prefixes "airline-base16_atelier_heath_light-theme" '("airline-base16_atelier_heath_light"))


;;; Generated autoloads from airline-base16_atelier_lakeside-theme.el

(register-definition-prefixes "airline-base16_atelier_lakeside-theme" '("airline-base16_atelier_lakeside"))


;;; Generated autoloads from airline-base16_atelier_lakeside_light-theme.el

(register-definition-prefixes "airline-base16_atelier_lakeside_light-theme" '("airline-base16_atelier_lakeside_light"))


;;; Generated autoloads from airline-base16_atelier_plateau-theme.el

(register-definition-prefixes "airline-base16_atelier_plateau-theme" '("airline-base16_atelier_plateau"))


;;; Generated autoloads from airline-base16_atelier_plateau_light-theme.el

(register-definition-prefixes "airline-base16_atelier_plateau_light-theme" '("airline-base16_atelier_plateau_light"))


;;; Generated autoloads from airline-base16_atelier_savanna-theme.el

(register-definition-prefixes "airline-base16_atelier_savanna-theme" '("airline-base16_atelier_savanna"))


;;; Generated autoloads from airline-base16_atelier_savanna_light-theme.el

(register-definition-prefixes "airline-base16_atelier_savanna_light-theme" '("airline-base16_atelier_savanna_light"))


;;; Generated autoloads from airline-base16_atelier_seaside-theme.el

(register-definition-prefixes "airline-base16_atelier_seaside-theme" '("airline-base16_atelier_seaside"))


;;; Generated autoloads from airline-base16_atelier_seaside_light-theme.el

(register-definition-prefixes "airline-base16_atelier_seaside_light-theme" '("airline-base16_atelier_seaside_light"))


;;; Generated autoloads from airline-base16_atelier_sulphurpool-theme.el

(register-definition-prefixes "airline-base16_atelier_sulphurpool-theme" '("airline-base16_atelier_sulphurpool"))


;;; Generated autoloads from airline-base16_atelier_sulphurpool_light-theme.el

(register-definition-prefixes "airline-base16_atelier_sulphurpool_light-theme" '("airline-base16_atelier_sulphurpool_light"))


;;; Generated autoloads from airline-base16_atelierdune-theme.el

(register-definition-prefixes "airline-base16_atelierdune-theme" '("airline-base16_atelierdune"))


;;; Generated autoloads from airline-base16_atelierforest-theme.el

(register-definition-prefixes "airline-base16_atelierforest-theme" '("airline-base16_atelierforest"))


;;; Generated autoloads from airline-base16_atelierheath-theme.el

(register-definition-prefixes "airline-base16_atelierheath-theme" '("airline-base16_atelierheath"))


;;; Generated autoloads from airline-base16_atelierlakeside-theme.el

(register-definition-prefixes "airline-base16_atelierlakeside-theme" '("airline-base16_atelierlakeside"))


;;; Generated autoloads from airline-base16_atelierseaside-theme.el

(register-definition-prefixes "airline-base16_atelierseaside-theme" '("airline-base16_atelierseaside"))


;;; Generated autoloads from airline-base16_atlas-theme.el

(register-definition-prefixes "airline-base16_atlas-theme" '("airline-base16_atlas"))


;;; Generated autoloads from airline-base16_bespin-theme.el

(register-definition-prefixes "airline-base16_bespin-theme" '("airline-base16_bespin"))


;;; Generated autoloads from airline-base16_black_metal-theme.el

(register-definition-prefixes "airline-base16_black_metal-theme" '("airline-base16_black_metal"))


;;; Generated autoloads from airline-base16_black_metal_bathory-theme.el

(register-definition-prefixes "airline-base16_black_metal_bathory-theme" '("airline-base16_black_metal_bathory"))


;;; Generated autoloads from airline-base16_black_metal_burzum-theme.el

(register-definition-prefixes "airline-base16_black_metal_burzum-theme" '("airline-base16_black_metal_burzum"))


;;; Generated autoloads from airline-base16_black_metal_dark_funeral-theme.el

(register-definition-prefixes "airline-base16_black_metal_dark_funeral-theme" '("airline-base16_black_metal_dark_funeral"))


;;; Generated autoloads from airline-base16_black_metal_gorgoroth-theme.el

(register-definition-prefixes "airline-base16_black_metal_gorgoroth-theme" '("airline-base16_black_metal_gorgoroth"))


;;; Generated autoloads from airline-base16_black_metal_immortal-theme.el

(register-definition-prefixes "airline-base16_black_metal_immortal-theme" '("airline-base16_black_metal_immortal"))


;;; Generated autoloads from airline-base16_black_metal_khold-theme.el

(register-definition-prefixes "airline-base16_black_metal_khold-theme" '("airline-base16_black_metal_khold"))


;;; Generated autoloads from airline-base16_black_metal_marduk-theme.el

(register-definition-prefixes "airline-base16_black_metal_marduk-theme" '("airline-base16_black_metal_marduk"))


;;; Generated autoloads from airline-base16_black_metal_mayhem-theme.el

(register-definition-prefixes "airline-base16_black_metal_mayhem-theme" '("airline-base16_black_metal_mayhem"))


;;; Generated autoloads from airline-base16_black_metal_nile-theme.el

(register-definition-prefixes "airline-base16_black_metal_nile-theme" '("airline-base16_black_metal_nile"))


;;; Generated autoloads from airline-base16_black_metal_venom-theme.el

(register-definition-prefixes "airline-base16_black_metal_venom-theme" '("airline-base16_black_metal_venom"))


;;; Generated autoloads from airline-base16_brewer-theme.el

(register-definition-prefixes "airline-base16_brewer-theme" '("airline-base16_brewer"))


;;; Generated autoloads from airline-base16_bright-theme.el

(register-definition-prefixes "airline-base16_bright-theme" '("airline-base16_bright"))


;;; Generated autoloads from airline-base16_brogrammer-theme.el

(register-definition-prefixes "airline-base16_brogrammer-theme" '("airline-base16_brogrammer"))


;;; Generated autoloads from airline-base16_brushtrees-theme.el

(register-definition-prefixes "airline-base16_brushtrees-theme" '("airline-base16_brushtrees"))


;;; Generated autoloads from airline-base16_brushtrees_dark-theme.el

(register-definition-prefixes "airline-base16_brushtrees_dark-theme" '("airline-base16_brushtrees_dark"))


;;; Generated autoloads from airline-base16_chalk-theme.el

(register-definition-prefixes "airline-base16_chalk-theme" '("airline-base16_chalk"))


;;; Generated autoloads from airline-base16_circus-theme.el

(register-definition-prefixes "airline-base16_circus-theme" '("airline-base16_circus"))


;;; Generated autoloads from airline-base16_classic-theme.el

(register-definition-prefixes "airline-base16_classic-theme" '("airline-base16_classic"))


;;; Generated autoloads from airline-base16_classic_dark-theme.el

(register-definition-prefixes "airline-base16_classic_dark-theme" '("airline-base16_classic_dark"))


;;; Generated autoloads from airline-base16_classic_light-theme.el

(register-definition-prefixes "airline-base16_classic_light-theme" '("airline-base16_classic_light"))


;;; Generated autoloads from airline-base16_codeschool-theme.el

(register-definition-prefixes "airline-base16_codeschool-theme" '("airline-base16_codeschool"))


;;; Generated autoloads from airline-base16_colors-theme.el

(register-definition-prefixes "airline-base16_colors-theme" '("airline-base16_colors"))


;;; Generated autoloads from airline-base16_cupcake-theme.el

(register-definition-prefixes "airline-base16_cupcake-theme" '("airline-base16_cupcake"))


;;; Generated autoloads from airline-base16_cupertino-theme.el

(register-definition-prefixes "airline-base16_cupertino-theme" '("airline-base16_cupertino"))


;;; Generated autoloads from airline-base16_darktooth-theme.el

(register-definition-prefixes "airline-base16_darktooth-theme" '("airline-base16_darktooth"))


;;; Generated autoloads from airline-base16_decaf-theme.el

(register-definition-prefixes "airline-base16_decaf-theme" '("airline-base16_decaf"))


;;; Generated autoloads from airline-base16_default-theme.el

(register-definition-prefixes "airline-base16_default-theme" '("airline-base16_default"))


;;; Generated autoloads from airline-base16_default_dark-theme.el

(register-definition-prefixes "airline-base16_default_dark-theme" '("airline-base16_default_dark"))


;;; Generated autoloads from airline-base16_default_light-theme.el

(register-definition-prefixes "airline-base16_default_light-theme" '("airline-base16_default_light"))


;;; Generated autoloads from airline-base16_dracula-theme.el

(register-definition-prefixes "airline-base16_dracula-theme" '("airline-base16_dracula"))


;;; Generated autoloads from airline-base16_edge_dark-theme.el

(register-definition-prefixes "airline-base16_edge_dark-theme" '("airline-base16_edge_dark"))


;;; Generated autoloads from airline-base16_edge_light-theme.el

(register-definition-prefixes "airline-base16_edge_light-theme" '("airline-base16_edge_light"))


;;; Generated autoloads from airline-base16_eighties-theme.el

(register-definition-prefixes "airline-base16_eighties-theme" '("airline-base16_eighties"))


;;; Generated autoloads from airline-base16_embers-theme.el

(register-definition-prefixes "airline-base16_embers-theme" '("airline-base16_embers"))


;;; Generated autoloads from airline-base16_espresso-theme.el

(register-definition-prefixes "airline-base16_espresso-theme" '("airline-base16_espresso"))


;;; Generated autoloads from airline-base16_flat-theme.el

(register-definition-prefixes "airline-base16_flat-theme" '("airline-base16_flat"))


;;; Generated autoloads from airline-base16_framer-theme.el

(register-definition-prefixes "airline-base16_framer-theme" '("airline-base16_framer"))


;;; Generated autoloads from airline-base16_fruit_soda-theme.el

(register-definition-prefixes "airline-base16_fruit_soda-theme" '("airline-base16_fruit_soda"))


;;; Generated autoloads from airline-base16_gigavolt-theme.el

(register-definition-prefixes "airline-base16_gigavolt-theme" '("airline-base16_gigavolt"))


;;; Generated autoloads from airline-base16_github-theme.el

(register-definition-prefixes "airline-base16_github-theme" '("airline-base16_github"))


;;; Generated autoloads from airline-base16_google-theme.el

(register-definition-prefixes "airline-base16_google-theme" '("airline-base16_google"))


;;; Generated autoloads from airline-base16_google_dark-theme.el

(register-definition-prefixes "airline-base16_google_dark-theme" '("airline-base16_google_dark"))


;;; Generated autoloads from airline-base16_google_light-theme.el

(register-definition-prefixes "airline-base16_google_light-theme" '("airline-base16_google_light"))


;;; Generated autoloads from airline-base16_grayscale-theme.el

(register-definition-prefixes "airline-base16_grayscale-theme" '("airline-base16_grayscale"))


;;; Generated autoloads from airline-base16_grayscale_dark-theme.el

(register-definition-prefixes "airline-base16_grayscale_dark-theme" '("airline-base16_grayscale_dark"))


;;; Generated autoloads from airline-base16_grayscale_light-theme.el

(register-definition-prefixes "airline-base16_grayscale_light-theme" '("airline-base16_grayscale_light"))


;;; Generated autoloads from airline-base16_greenscreen-theme.el

(register-definition-prefixes "airline-base16_greenscreen-theme" '("airline-base16_greenscreen"))


;;; Generated autoloads from airline-base16_gruvbox_dark_hard-theme.el

(register-definition-prefixes "airline-base16_gruvbox_dark_hard-theme" '("airline-base16_gruvbox_dark_hard"))


;;; Generated autoloads from airline-base16_gruvbox_dark_medium-theme.el

(register-definition-prefixes "airline-base16_gruvbox_dark_medium-theme" '("airline-base16_gruvbox_dark_medium"))


;;; Generated autoloads from airline-base16_gruvbox_dark_pale-theme.el

(register-definition-prefixes "airline-base16_gruvbox_dark_pale-theme" '("airline-base16_gruvbox_dark_pale"))


;;; Generated autoloads from airline-base16_gruvbox_dark_soft-theme.el

(register-definition-prefixes "airline-base16_gruvbox_dark_soft-theme" '("airline-base16_gruvbox_dark_soft"))


;;; Generated autoloads from airline-base16_gruvbox_light_hard-theme.el

(register-definition-prefixes "airline-base16_gruvbox_light_hard-theme" '("airline-base16_gruvbox_light_hard"))


;;; Generated autoloads from airline-base16_gruvbox_light_medium-theme.el

(register-definition-prefixes "airline-base16_gruvbox_light_medium-theme" '("airline-base16_gruvbox_light_medium"))


;;; Generated autoloads from airline-base16_gruvbox_light_soft-theme.el

(register-definition-prefixes "airline-base16_gruvbox_light_soft-theme" '("airline-base16_gruvbox_light_soft"))


;;; Generated autoloads from airline-base16_harmonic16-theme.el

(register-definition-prefixes "airline-base16_harmonic16-theme" '("airline-base16_harmonic16"))


;;; Generated autoloads from airline-base16_harmonic_dark-theme.el

(register-definition-prefixes "airline-base16_harmonic_dark-theme" '("airline-base16_harmonic_dark"))


;;; Generated autoloads from airline-base16_harmonic_light-theme.el

(register-definition-prefixes "airline-base16_harmonic_light-theme" '("airline-base16_harmonic_light"))


;;; Generated autoloads from airline-base16_heetch-theme.el

(register-definition-prefixes "airline-base16_heetch-theme" '("airline-base16_heetch"))


;;; Generated autoloads from airline-base16_heetch_light-theme.el

(register-definition-prefixes "airline-base16_heetch_light-theme" '("airline-base16_heetch_light"))


;;; Generated autoloads from airline-base16_helios-theme.el

(register-definition-prefixes "airline-base16_helios-theme" '("airline-base16_helios"))


;;; Generated autoloads from airline-base16_hopscotch-theme.el

(register-definition-prefixes "airline-base16_hopscotch-theme" '("airline-base16_hopscotch"))


;;; Generated autoloads from airline-base16_horizon_dark-theme.el

(register-definition-prefixes "airline-base16_horizon_dark-theme" '("airline-base16_horizon_dark"))


;;; Generated autoloads from airline-base16_horizon_light-theme.el

(register-definition-prefixes "airline-base16_horizon_light-theme" '("airline-base16_horizon_light"))


;;; Generated autoloads from airline-base16_horizon_terminal_dark-theme.el

(register-definition-prefixes "airline-base16_horizon_terminal_dark-theme" '("airline-base16_horizon_terminal_dark"))


;;; Generated autoloads from airline-base16_horizon_terminal_light-theme.el

(register-definition-prefixes "airline-base16_horizon_terminal_light-theme" '("airline-base16_horizon_terminal_light"))


;;; Generated autoloads from airline-base16_ia_dark-theme.el

(register-definition-prefixes "airline-base16_ia_dark-theme" '("airline-base16_ia_dark"))


;;; Generated autoloads from airline-base16_ia_light-theme.el

(register-definition-prefixes "airline-base16_ia_light-theme" '("airline-base16_ia_light"))


;;; Generated autoloads from airline-base16_icy-theme.el

(register-definition-prefixes "airline-base16_icy-theme" '("airline-base16_icy"))


;;; Generated autoloads from airline-base16_irblack-theme.el

(register-definition-prefixes "airline-base16_irblack-theme" '("airline-base16_irblack"))


;;; Generated autoloads from airline-base16_isotope-theme.el

(register-definition-prefixes "airline-base16_isotope-theme" '("airline-base16_isotope"))


;;; Generated autoloads from airline-base16_londontube-theme.el

(register-definition-prefixes "airline-base16_londontube-theme" '("airline-base16_londontube"))


;;; Generated autoloads from airline-base16_macintosh-theme.el

(register-definition-prefixes "airline-base16_macintosh-theme" '("airline-base16_macintosh"))


;;; Generated autoloads from airline-base16_marrakesh-theme.el

(register-definition-prefixes "airline-base16_marrakesh-theme" '("airline-base16_marrakesh"))


;;; Generated autoloads from airline-base16_materia-theme.el

(register-definition-prefixes "airline-base16_materia-theme" '("airline-base16_materia"))


;;; Generated autoloads from airline-base16_material-theme.el

(register-definition-prefixes "airline-base16_material-theme" '("airline-base16_material"))


;;; Generated autoloads from airline-base16_material_darker-theme.el

(register-definition-prefixes "airline-base16_material_darker-theme" '("airline-base16_material_darker"))


;;; Generated autoloads from airline-base16_material_lighter-theme.el

(register-definition-prefixes "airline-base16_material_lighter-theme" '("airline-base16_material_lighter"))


;;; Generated autoloads from airline-base16_material_palenight-theme.el

(register-definition-prefixes "airline-base16_material_palenight-theme" '("airline-base16_material_palenight"))


;;; Generated autoloads from airline-base16_material_vivid-theme.el

(register-definition-prefixes "airline-base16_material_vivid-theme" '("airline-base16_material_vivid"))


;;; Generated autoloads from airline-base16_mellow_purple-theme.el

(register-definition-prefixes "airline-base16_mellow_purple-theme" '("airline-base16_mellow_purple"))


;;; Generated autoloads from airline-base16_mexico_light-theme.el

(register-definition-prefixes "airline-base16_mexico_light-theme" '("airline-base16_mexico_light"))


;;; Generated autoloads from airline-base16_mocha-theme.el

(register-definition-prefixes "airline-base16_mocha-theme" '("airline-base16_mocha"))


;;; Generated autoloads from airline-base16_monokai-theme.el

(register-definition-prefixes "airline-base16_monokai-theme" '("airline-base16_monokai"))


;;; Generated autoloads from airline-base16_nord-theme.el

(register-definition-prefixes "airline-base16_nord-theme" '("airline-base16_nord"))


;;; Generated autoloads from airline-base16_nova-theme.el

(register-definition-prefixes "airline-base16_nova-theme" '("airline-base16_nova"))


;;; Generated autoloads from airline-base16_ocean-theme.el

(register-definition-prefixes "airline-base16_ocean-theme" '("airline-base16_ocean"))


;;; Generated autoloads from airline-base16_oceanicnext-theme.el

(register-definition-prefixes "airline-base16_oceanicnext-theme" '("airline-base16_oceanicnext"))


;;; Generated autoloads from airline-base16_one_light-theme.el

(register-definition-prefixes "airline-base16_one_light-theme" '("airline-base16_one_light"))


;;; Generated autoloads from airline-base16_onedark-theme.el

(register-definition-prefixes "airline-base16_onedark-theme" '("airline-base16_onedark"))


;;; Generated autoloads from airline-base16_outrun_dark-theme.el

(register-definition-prefixes "airline-base16_outrun_dark-theme" '("airline-base16_outrun_dark"))


;;; Generated autoloads from airline-base16_papercolor_dark-theme.el

(register-definition-prefixes "airline-base16_papercolor_dark-theme" '("airline-base16_papercolor_dark"))


;;; Generated autoloads from airline-base16_papercolor_light-theme.el

(register-definition-prefixes "airline-base16_papercolor_light-theme" '("airline-base16_papercolor_light"))


;;; Generated autoloads from airline-base16_paraiso-theme.el

(register-definition-prefixes "airline-base16_paraiso-theme" '("airline-base16_paraiso"))


;;; Generated autoloads from airline-base16_phd-theme.el

(register-definition-prefixes "airline-base16_phd-theme" '("airline-base16_phd"))


;;; Generated autoloads from airline-base16_pico-theme.el

(register-definition-prefixes "airline-base16_pico-theme" '("airline-base16_pico"))


;;; Generated autoloads from airline-base16_pop-theme.el

(register-definition-prefixes "airline-base16_pop-theme" '("airline-base16_pop"))


;;; Generated autoloads from airline-base16_porple-theme.el

(register-definition-prefixes "airline-base16_porple-theme" '("airline-base16_porple"))


;;; Generated autoloads from airline-base16_railscasts-theme.el

(register-definition-prefixes "airline-base16_railscasts-theme" '("airline-base16_railscasts"))


;;; Generated autoloads from airline-base16_rebecca-theme.el

(register-definition-prefixes "airline-base16_rebecca-theme" '("airline-base16_rebecca"))


;;; Generated autoloads from airline-base16_sandcastle-theme.el

(register-definition-prefixes "airline-base16_sandcastle-theme" '("airline-base16_sandcastle"))


;;; Generated autoloads from airline-base16_seti-theme.el

(register-definition-prefixes "airline-base16_seti-theme" '("airline-base16_seti"))


;;; Generated autoloads from airline-base16_shapeshifter-theme.el

(register-definition-prefixes "airline-base16_shapeshifter-theme" '("airline-base16_shapeshifter"))


;;; Generated autoloads from airline-base16_shell-theme.el

(register-definition-prefixes "airline-base16_shell-theme" '("airline-base16_shell"))


;;; Generated autoloads from airline-base16_snazzy-theme.el

(register-definition-prefixes "airline-base16_snazzy-theme" '("airline-base16_snazzy"))


;;; Generated autoloads from airline-base16_solarflare-theme.el

(register-definition-prefixes "airline-base16_solarflare-theme" '("airline-base16_solarflare"))


;;; Generated autoloads from airline-base16_solarized-theme.el

(register-definition-prefixes "airline-base16_solarized-theme" '("airline-base16_solarized"))


;;; Generated autoloads from airline-base16_solarized_dark-theme.el

(register-definition-prefixes "airline-base16_solarized_dark-theme" '("airline-base16_solarized_dark"))


;;; Generated autoloads from airline-base16_solarized_light-theme.el

(register-definition-prefixes "airline-base16_solarized_light-theme" '("airline-base16_solarized_light"))


;;; Generated autoloads from airline-base16_spacemacs-theme.el

(register-definition-prefixes "airline-base16_spacemacs-theme" '("airline-base16_spacemacs"))


;;; Generated autoloads from airline-base16_summerfruit-theme.el

(register-definition-prefixes "airline-base16_summerfruit-theme" '("airline-base16_summerfruit"))


;;; Generated autoloads from airline-base16_summerfruit_dark-theme.el

(register-definition-prefixes "airline-base16_summerfruit_dark-theme" '("airline-base16_summerfruit_dark"))


;;; Generated autoloads from airline-base16_summerfruit_light-theme.el

(register-definition-prefixes "airline-base16_summerfruit_light-theme" '("airline-base16_summerfruit_light"))


;;; Generated autoloads from airline-base16_synth_midnight_dark-theme.el

(register-definition-prefixes "airline-base16_synth_midnight_dark-theme" '("airline-base16_synth_midnight_dark"))


;;; Generated autoloads from airline-base16_tomorrow-theme.el

(register-definition-prefixes "airline-base16_tomorrow-theme" '("airline-base16_tomorrow"))


;;; Generated autoloads from airline-base16_tomorrow_night-theme.el

(register-definition-prefixes "airline-base16_tomorrow_night-theme" '("airline-base16_tomorrow_night"))


;;; Generated autoloads from airline-base16_tomorrow_night_eighties-theme.el

(register-definition-prefixes "airline-base16_tomorrow_night_eighties-theme" '("airline-base16_tomorrow_night_eighties"))


;;; Generated autoloads from airline-base16_tube-theme.el

(register-definition-prefixes "airline-base16_tube-theme" '("airline-base16_tube"))


;;; Generated autoloads from airline-base16_twilight-theme.el

(register-definition-prefixes "airline-base16_twilight-theme" '("airline-base16_twilight"))


;;; Generated autoloads from airline-base16_unikitty_dark-theme.el

(register-definition-prefixes "airline-base16_unikitty_dark-theme" '("airline-base16_unikitty_dark"))


;;; Generated autoloads from airline-base16_unikitty_light-theme.el

(register-definition-prefixes "airline-base16_unikitty_light-theme" '("airline-base16_unikitty_light"))


;;; Generated autoloads from airline-base16_vim-theme.el

(register-definition-prefixes "airline-base16_vim-theme" '("airline-base16_vim"))


;;; Generated autoloads from airline-base16_woodland-theme.el

(register-definition-prefixes "airline-base16_woodland-theme" '("airline-base16_woodland"))


;;; Generated autoloads from airline-base16_xcode_dusk-theme.el

(register-definition-prefixes "airline-base16_xcode_dusk-theme" '("airline-base16_xcode_dusk"))


;;; Generated autoloads from airline-base16_zenburn-theme.el

(register-definition-prefixes "airline-base16_zenburn-theme" '("airline-base16_zenburn"))


;;; Generated autoloads from airline-base16color-theme.el

(register-definition-prefixes "airline-base16color-theme" '("airline-base16color"))


;;; Generated autoloads from airline-behelit-theme.el

(register-definition-prefixes "airline-behelit-theme" '("airline-behelit"))


;;; Generated autoloads from airline-biogoo-theme.el

(register-definition-prefixes "airline-biogoo-theme" '("airline-biogoo"))


;;; Generated autoloads from airline-blood_red-theme.el

(register-definition-prefixes "airline-blood_red-theme" '("airline-blood_red"))


;;; Generated autoloads from airline-bubblegum-theme.el

(register-definition-prefixes "airline-bubblegum-theme" '("airline-bubblegum"))


;;; Generated autoloads from airline-catppuccin_frappe-theme.el

(register-definition-prefixes "airline-catppuccin_frappe-theme" '("airline-catppuccin_frappe"))


;;; Generated autoloads from airline-catppuccin_latte-theme.el

(register-definition-prefixes "airline-catppuccin_latte-theme" '("airline-catppuccin_latte"))


;;; Generated autoloads from airline-catppuccin_macchiato-theme.el

(register-definition-prefixes "airline-catppuccin_macchiato-theme" '("airline-catppuccin_macchiato"))


;;; Generated autoloads from airline-catppuccin_mocha-theme.el

(register-definition-prefixes "airline-catppuccin_mocha-theme" '("airline-catppuccin_mocha"))


;;; Generated autoloads from airline-cobalt2-theme.el

(register-definition-prefixes "airline-cobalt2-theme" '("airline-cobalt2"))


;;; Generated autoloads from airline-cool-theme.el

(register-definition-prefixes "airline-cool-theme" '("airline-cool"))


;;; Generated autoloads from airline-cyberpunk-theme.el

(register-definition-prefixes "airline-cyberpunk-theme" '("airline-cyberpunk"))


;;; Generated autoloads from airline-dark-theme.el

(register-definition-prefixes "airline-dark-theme" '("airline-dark"))


;;; Generated autoloads from airline-dark_minimal-theme.el

(register-definition-prefixes "airline-dark_minimal-theme" '("airline-dark_minimal"))


;;; Generated autoloads from airline-desertink-theme.el

(register-definition-prefixes "airline-desertink-theme" '("airline-desertink"))


;;; Generated autoloads from airline-deus-theme.el

(register-definition-prefixes "airline-deus-theme" '("airline-deus"))


;;; Generated autoloads from airline-distinguished-theme.el

(register-definition-prefixes "airline-distinguished-theme" '("airline-distinguished"))


;;; Generated autoloads from airline-doom-molokai-theme.el

(register-definition-prefixes "airline-doom-molokai-theme" '("airline-doom-molokai"))


;;; Generated autoloads from airline-doom-one-theme.el

(register-definition-prefixes "airline-doom-one-theme" '("airline-doom-one"))


;;; Generated autoloads from airline-durant-theme.el

(register-definition-prefixes "airline-durant-theme" '("airline-durant"))


;;; Generated autoloads from airline-fairyfloss-theme.el

(register-definition-prefixes "airline-fairyfloss-theme" '("airline-fairyfloss"))


;;; Generated autoloads from airline-fruit_punch-theme.el

(register-definition-prefixes "airline-fruit_punch-theme" '("airline-fruit_punch"))


;;; Generated autoloads from airline-google_dark-theme.el

(register-definition-prefixes "airline-google_dark-theme" '("airline-google_dark"))


;;; Generated autoloads from airline-google_light-theme.el

(register-definition-prefixes "airline-google_light-theme" '("airline-google_light"))


;;; Generated autoloads from airline-gruvbox-dark-theme.el

(register-definition-prefixes "airline-gruvbox-dark-theme" '("airline-gruvbox-dark"))


;;; Generated autoloads from airline-hybrid-theme.el

(register-definition-prefixes "airline-hybrid-theme" '("airline-hybrid"))


;;; Generated autoloads from airline-hybridline-theme.el

(register-definition-prefixes "airline-hybridline-theme" '("airline-hybridline"))


;;; Generated autoloads from airline-jellybeans-theme.el

(register-definition-prefixes "airline-jellybeans-theme" '("airline-jellybeans"))


;;; Generated autoloads from airline-jet-theme.el

(register-definition-prefixes "airline-jet-theme" '("airline-jet"))


;;; Generated autoloads from airline-kalisi-theme.el

(register-definition-prefixes "airline-kalisi-theme" '("airline-kalisi"))


;;; Generated autoloads from airline-kolor-theme.el

(register-definition-prefixes "airline-kolor-theme" '("airline-kolor"))


;;; Generated autoloads from airline-laederon-theme.el

(register-definition-prefixes "airline-laederon-theme" '("airline-laederon"))


;;; Generated autoloads from airline-lessnoise-theme.el

(register-definition-prefixes "airline-lessnoise-theme" '("airline-lessnoise"))


;;; Generated autoloads from airline-light-theme.el

(register-definition-prefixes "airline-light-theme" '("airline-light"))


;;; Generated autoloads from airline-lighthaus-theme.el

(register-definition-prefixes "airline-lighthaus-theme" '("airline-lighthaus"))


;;; Generated autoloads from airline-lucius-theme.el

(register-definition-prefixes "airline-lucius-theme" '("airline-lucius"))


;;; Generated autoloads from airline-luna-theme.el

(register-definition-prefixes "airline-luna-theme" '("airline-luna"))


;;; Generated autoloads from airline-minimalist-theme.el

(register-definition-prefixes "airline-minimalist-theme" '("airline-minimalist"))


;;; Generated autoloads from airline-molokai-theme.el

(register-definition-prefixes "airline-molokai-theme" '("airline-molokai"))


;;; Generated autoloads from airline-monochrome-theme.el

(register-definition-prefixes "airline-monochrome-theme" '("airline-monochrome"))


;;; Generated autoloads from airline-murmur-theme.el

(register-definition-prefixes "airline-murmur-theme" '("airline-murmur"))


;;; Generated autoloads from airline-night_owl-theme.el

(register-definition-prefixes "airline-night_owl-theme" '("airline-night_owl"))


;;; Generated autoloads from airline-nord_minimal-theme.el

(register-definition-prefixes "airline-nord_minimal-theme" '("airline-nord_minimal"))


;;; Generated autoloads from airline-onedark-theme.el

(register-definition-prefixes "airline-onedark-theme" '("airline-onedark"))


;;; Generated autoloads from airline-ouo-theme.el

(register-definition-prefixes "airline-ouo-theme" '("airline-ouo"))


;;; Generated autoloads from airline-owo-theme.el

(register-definition-prefixes "airline-owo-theme" '("airline-owo"))


;;; Generated autoloads from airline-papercolor-theme.el

(register-definition-prefixes "airline-papercolor-theme" '("airline-papercolor"))


;;; Generated autoloads from airline-peaksea-theme.el

(register-definition-prefixes "airline-peaksea-theme" '("airline-peaksea"))


;;; Generated autoloads from airline-powerlineish-theme.el

(register-definition-prefixes "airline-powerlineish-theme" '("airline-powerlineish"))


;;; Generated autoloads from airline-qwq-theme.el

(register-definition-prefixes "airline-qwq-theme" '("airline-qwq"))


;;; Generated autoloads from airline-raven-theme.el

(register-definition-prefixes "airline-raven-theme" '("airline-raven"))


;;; Generated autoloads from airline-ravenpower-theme.el

(register-definition-prefixes "airline-ravenpower-theme" '("airline-ravenpower"))


;;; Generated autoloads from airline-seagull-theme.el

(register-definition-prefixes "airline-seagull-theme" '("airline-seagull"))


;;; Generated autoloads from airline-selenized-theme.el

(register-definition-prefixes "airline-selenized-theme" '("airline-selenized"))


;;; Generated autoloads from airline-selenized_bw-theme.el

(register-definition-prefixes "airline-selenized_bw-theme" '("airline-selenized_bw"))


;;; Generated autoloads from airline-seoul256-theme.el

(register-definition-prefixes "airline-seoul256-theme" '("airline-seoul256"))


;;; Generated autoloads from airline-serene-theme.el

(register-definition-prefixes "airline-serene-theme" '("airline-serene"))


;;; Generated autoloads from airline-sierra-theme.el

(register-definition-prefixes "airline-sierra-theme" '("airline-sierra"))


;;; Generated autoloads from airline-silver-theme.el

(register-definition-prefixes "airline-silver-theme" '("airline-silver"))


;;; Generated autoloads from airline-simple-theme.el

(register-definition-prefixes "airline-simple-theme" '("airline-simple"))


;;; Generated autoloads from airline-soda-theme.el

(register-definition-prefixes "airline-soda-theme" '("airline-soda"))


;;; Generated autoloads from airline-sol-theme.el

(register-definition-prefixes "airline-sol-theme" '("airline-sol"))


;;; Generated autoloads from airline-solarized-alternate-gui-theme.el

(register-definition-prefixes "airline-solarized-alternate-gui-theme" '("airline-solarized-alternate-gui"))


;;; Generated autoloads from airline-solarized-gui-theme.el

(register-definition-prefixes "airline-solarized-gui-theme" '("airline-solarized-gui"))


;;; Generated autoloads from airline-solarized-theme.el

(register-definition-prefixes "airline-solarized-theme" '("airline-solarized"))


;;; Generated autoloads from airline-solarized_flood-theme.el

(register-definition-prefixes "airline-solarized_flood-theme" '("airline-solarized_flood"))


;;; Generated autoloads from airline-supernova-theme.el

(register-definition-prefixes "airline-supernova-theme" '("airline-supernova"))


;;; Generated autoloads from airline-term-theme.el

(register-definition-prefixes "airline-term-theme" '("airline-term"))


;;; Generated autoloads from airline-term_light-theme.el

(register-definition-prefixes "airline-term_light-theme" '("airline-term_light"))


;;; Generated autoloads from airline-themes.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "airline-themes" '("airline-"))


;;; Generated autoloads from airline-tomorrow-theme.el

(register-definition-prefixes "airline-tomorrow-theme" '("airline-tomorrow"))


;;; Generated autoloads from airline-transparent-theme.el

(register-definition-prefixes "airline-transparent-theme" '("airline-transparent"))


;;; Generated autoloads from airline-ubaryd-theme.el

(register-definition-prefixes "airline-ubaryd-theme" '("airline-ubaryd"))


;;; Generated autoloads from airline-understated-theme.el

(register-definition-prefixes "airline-understated-theme" '("airline-understated"))


;;; Generated autoloads from airline-violet-theme.el

(register-definition-prefixes "airline-violet-theme" '("airline-violet"))


;;; Generated autoloads from airline-wombat-theme.el

(register-definition-prefixes "airline-wombat-theme" '("airline-wombat"))


;;; Generated autoloads from airline-xtermlight-theme.el

(register-definition-prefixes "airline-xtermlight-theme" '("airline-xtermlight"))


;;; Generated autoloads from airline-zenburn-theme.el

(register-definition-prefixes "airline-zenburn-theme" '("airline-zenburn"))

;;; End of scraped data

(provide 'airline-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; airline-themes-autoloads.el ends here
