;;; direx-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from direx.el

(autoload 'direx:jump-to-directory "direx" nil t)
(autoload 'direx:jump-to-directory-other-window "direx" nil t)
(register-definition-prefixes "direx" '("direx:"))


;;; Generated autoloads from direx-project.el

(autoload 'direx-project:jump-to-project-root "direx-project" nil t)
(autoload 'direx-project:jump-to-project-root-other-window "direx-project" nil t)
(register-definition-prefixes "direx-project" '("direx-project:"))

;;; End of scraped data

(provide 'direx-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; direx-autoloads.el ends here
