;;; gist-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gist.el

(autoload 'gist-region "gist" "\
Post the current region as a new paste at gist.github.com
Copies the URL into the kill ring.

With a prefix argument, makes a private paste.

(fn BEGIN END &optional PRIVATE CALLBACK)" t)
(autoload 'gist-region-private "gist" "\
Post the current region as a new private paste at gist.github.com
Copies the URL into the kill ring.

(fn BEGIN END)" t)
(autoload 'gist-buffer "gist" "\
Post the current buffer as a new paste at gist.github.com.
Copies the URL into the kill ring.

With a prefix argument, makes a private paste.

(fn &optional PRIVATE)" t)
(autoload 'gist-buffer-private "gist" "\
Post the current buffer as a new private paste at gist.github.com.
Copies the URL into the kill ring." t)
(autoload 'gist-region-or-buffer "gist" "\
Post either the current region, or if mark is not set, the
  current buffer as a new paste at gist.github.com

Copies the URL into the kill ring.

With a prefix argument, makes a private paste.

(fn &optional PRIVATE)" t)
(autoload 'gist-region-or-buffer-private "gist" "\
Post either the current region, or if mark is not set, the
  current buffer as a new private paste at gist.github.com

Copies the URL into the kill ring." t)
(autoload 'gist-list-user "gist" "\
Displays a list of a user's gists in a new buffer.  When called from
  a program, pass 'current-user as the username to view the user's own
  gists, or nil for the username and a non-nil value for force-reload to
  reload the gists for the current buffer.

(fn USERNAME &optional FORCE-RELOAD BACKGROUND)" t)
(autoload 'gist-list "gist" "\
Displays a list of all of the current user's gists in a new buffer.

(fn &optional FORCE-RELOAD BACKGROUND)" t)
(autoload 'gist-fetch "gist" "\


(fn ID)" t)
(autoload 'gist-star "gist" nil t)
(autoload 'gist-unstar "gist" nil t)
(autoload 'gist-list-starred "gist" "\
List your starred gists.

(fn &optional BACKGROUND)" t)
(autoload 'gist-fork "gist" "\
Fork a gist." t)
(register-definition-prefixes "gist" '("dired-do-gist" "gist-"))

;;; End of scraped data

(provide 'gist-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gist-autoloads.el ends here
