;;; org-ac-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-ac.el

(autoload 'org-ac/setup-current-buffer "org-ac" "\
Do setup for using org-ac in current buffer." t)
(autoload 'org-ac/config-default "org-ac" "\
Do setting recommemded configuration.")
(register-definition-prefixes "org-ac" '("ac-source-org-ac-" "org-ac"))

;;; End of scraped data

(provide 'org-ac-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-ac-autoloads.el ends here
