;;; remember-last-theme-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from remember-last-theme.el

(autoload 'remember-last-theme-enable "remember-last-theme" "\
Ensure that the current theme(s) will be saved when Emacs exits." t)
(autoload 'remember-last-theme-with-file-enable "remember-last-theme" "\
Ensure that the current theme(s) will be saved when Emacs exits.

(fn FILENAME)" t)
(register-definition-prefixes "remember-last-theme" '("remember-last-theme-"))

;;; End of scraped data

(provide 'remember-last-theme-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; remember-last-theme-autoloads.el ends here
