;;; bazel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from bazel.el

(autoload 'bazel-build-mode "bazel" "\
Major mode for editing Bazel BUILD files.

(fn)" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (or "BUILD" "BUILD.bazel") eos) #'bazel-build-mode))
(autoload 'bazel-workspace-mode "bazel" "\
Major mode for editing Bazel WORKSPACE files.

(fn)" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (or "WORKSPACE" "WORKSPACE.bazel" "WORKSPACE.bzlmod") eos) #'bazel-workspace-mode))
(autoload 'bazel-module-mode "bazel" "\
Major mode for editing Bazel module files.

(fn)" t)
(add-to-list 'auto-mode-alist (cons (rx "/MODULE.bazel" eos) #'bazel-module-mode))
(autoload 'bazel-starlark-mode "bazel" "\
Major mode for editing Bazel Starlark files.

(fn)" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (+ nonl) ".bzl" eos) #'bazel-starlark-mode))
(autoload 'bazelrc-mode "bazel" "\
Major mode for editing .bazelrc files.

(fn)" t)
(add-to-list 'auto-mode-alist (cons (rx 47 (or "bazel.bazelrc" ".bazelrc") eos) #'bazelrc-mode))
(add-to-list 'auto-mode-alist (cons (rx "/.bazelignore" eos) #'bazelignore-mode))
(autoload 'bazelignore-mode "bazel" "\
Major mode for editing .bazelignore files.

(fn)" t)
(autoload 'bazeliskrc-mode "bazel" "\


(fn)" t)
(add-to-list 'auto-mode-alist (cons (rx "/.bazeliskrc" eos) #'bazeliskrc-mode))
(register-definition-prefixes "bazel" '("bazel"))

;;; End of scraped data

(provide 'bazel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; bazel-autoloads.el ends here
