;;; projectile-speedbar-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from projectile-speedbar.el

(autoload 'projectile-speedbar-open-current-buffer-in-tree "projectile-speedbar" nil t)
(autoload 'projectile-speedbar-toggle "projectile-speedbar" nil t)
(register-definition-prefixes "projectile-speedbar" '("projectile-speedbar-"))

;;; End of scraped data

(provide 'projectile-speedbar-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; projectile-speedbar-autoloads.el ends here
