;;; emamux-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from emamux.el

(autoload 'emamux:send-command "emamux" "\
Send command to target-session of tmux

(fn &optional COMMAND TARGET)" t)
(autoload 'emamux:send-region "emamux" "\
Send region to target-session of tmux

(fn BEG END)" t)
(autoload 'emamux:copy-kill-ring "emamux" "\
Set (car kill-ring) to tmux buffer

(fn ARG)" t)
(autoload 'emamux:yank-from-list-buffers "emamux" nil t)
(autoload 'emamux:kill-session "emamux" "\
Kill tmux session" t)
(autoload 'emamux:run-command "emamux" "\
Run command

(fn CMD &optional CMDDIR)" t)
(autoload 'emamux:run-last-command "emamux" nil t)
(autoload 'emamux:close-runner-pane "emamux" "\
Close runner pane" t)
(autoload 'emamux:close-panes "emamux" "\
Close all panes except current pane" t)
(autoload 'emamux:inspect-runner "emamux" "\
Enter copy-mode in runner pane" t)
(autoload 'emamux:interrupt-runner "emamux" "\
Send SIGINT to runner pane" t)
(autoload 'emamux:clear-runner-history "emamux" "\
Clear history of runner pane" t)
(autoload 'emamux:zoom-runner "emamux" "\
Zoom runner pane. This feature requires tmux 1.8 or higher" t)
(autoload 'emamux:new-window "emamux" "\
Create new window by cd-ing to current directory.
With prefix-arg, use '-a' option to insert the new window next to current index." t)
(autoload 'emamux:clone-current-frame "emamux" "\
Clones current frame into a new tmux window.
With prefix-arg, use '-a' option to insert the new window next to current index." t)
(autoload 'emamux:split-window "emamux" nil t)
(autoload 'emamux:split-window-horizontally "emamux" nil t)
(autoload 'emamux:run-region "emamux" "\
Send region to runner pane.

(fn BEG END)" t)
(register-definition-prefixes "emamux" '("emamux:"))

;;; End of scraped data

(provide 'emamux-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emamux-autoloads.el ends here
