- name: Download Go
  get_url: url=http://golang.org/dl/go{{go_version}}.linux-amd64.tar.gz
           dest=/usr/src/go{{go_version}}.tar.gz
- name: Get current Go version
  command: /usr/local/go/bin/go version
  register: go_current_version
  ignore_errors: true
  changed_when: "' go' + go_version + ' ' not in go_current_version.stdout|default('')"
- name: Delete outdated Go
  file: path='{{item}}' state=absent
  with_items:
    - '/usr/local/go/'
    - '/usr/local/lib/go/'
  when: go_current_version.changed
- name: Extract Go
  unarchive: src=/usr/src/go{{go_version}}.tar.gz copy=no dest=/usr/local/
             creates=/usr/local/go/bin/go
- name: Put Go into $PATH
  copy: dest=/etc/profile.d/go.sh mode=0644 owner=root group=root
        content="export PATH=/usr/local/lib/go/bin:/usr/local/go/bin/:$PATH\n"
- name: Export Go executable fact
  set_fact: go_executable='/usr/local/go/bin/go'
