;;; company-web-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-web.el

(register-definition-prefixes "company-web" '("company-web-"))


;;; Generated autoloads from company-web-html.el

(autoload 'company-web-html "company-web-html" "\
`company-mode' completion back-end for `html-mode' and `web-mode'.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-web-html" '("company-web-html-"))


;;; Generated autoloads from company-web-jade.el

(autoload 'company-web-jade "company-web-jade" "\
`company-mode' completion back-end for `jade-mode'.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-web-jade" '("company-web-jade-"))


;;; Generated autoloads from company-web-slim.el

(autoload 'company-web-slim "company-web-slim" "\
`company-mode' completion back-end for `slim-mode'.

(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "company-web-slim" '("company-web-slim-"))

;;; End of scraped data

(provide 'company-web-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-web-autoloads.el ends here
