;;; helm-navi-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-navi.el

(defalias 'helm-navi 'helm-navi-headings-and-keywords-current-buffer)
(autoload 'helm-navi-headings-and-keywords-current-buffer "helm-navi" "\
Show matches for all `navi-mode' keywords and `outshine' headings in current buffer." t)
(defalias 'helm-navi-headings 'helm-navi-headings-current-buffer)
(autoload 'helm-navi-headings-current-buffer "helm-navi" "\
Show matches for Outshine headings in current buffer." t)
(register-definition-prefixes "helm-navi" '("helm-"))

;;; End of scraped data

(provide 'helm-navi-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-navi-autoloads.el ends here
