- name: Download scalastyle
  get_url: url=https://oss.sonatype.org/content/repositories/releases/org/scalastyle/scalastyle-batch_2.10/{{scalastyle_version}}/scalastyle-batch_2.10-{{scalastyle_version}}-distribution.zip
           dest=/usr/src/scalastyle-batch_2.10-{{scalastyle_version}}-distribution.zip
- name: Extract scalastyle
  unarchive: src=/usr/src/scalastyle-batch_2.10-{{scalastyle_version}}-distribution.zip copy=no dest=/opt/
