;;; helm-pages-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from helm-pages.el

(autoload 'helm-pages "helm-pages" "\
View the pages in the current buffer with Helm." t)
(register-definition-prefixes "helm-pages" '("helm-pages-"))

;;; End of scraped data

(provide 'helm-pages-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; helm-pages-autoloads.el ends here
