;;; outshine-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from outshine.el

(autoload 'outshine-mode "outshine" "\
Outshine brings the look&feel of Org-mode to the (GNU Emacs)

world outside of the Org major-mode.

This is a minor mode.  If called interactively, toggle the
`Outshine mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `outshine-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'outshine-hook-function "outshine" "\
DEPRECATED, use `outshine-mode'.")
(register-definition-prefixes "outshine" '("outshine-"))


;;; Generated autoloads from outshine-org-cmds.el

(register-definition-prefixes "outshine-org-cmds" '("outshine-"))

;;; End of scraped data

(provide 'outshine-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; outshine-autoloads.el ends here
