#!/bin/bash
#chkconfig: 345 95 50
#description: Starts xvfb on display 98

export USER="abelardojara"
DISPLAY="98"
HOME="/home/$USER"

if [ -z "$1" ]; then
echo "`basename $0` {start|stop}"
exit
fi

case "$1" in
   start)
        su $USER -c "xinit -- /usr/bin/Xvfb :${DISPLAY} -screen 0 1900x1280x24 -ac +extension GLX +render -noreset" &
        su $USER -c "x11vnc -display :${DISPLAY} -bg -forever -rfbauth /home/${USER}/.vnc/passwd" &
	e=$?
	if [ $e -eq 1 ]; then
	  echo "Server is already running."
	  return
	fi

	if [ $e -eq 255 ]; then
	  echo "Server couldn't start."
	  exit 1
	fi
	DISPLAY=:${DISPLAY} su $USER -c "x-window-manager" &
	echo "[done]"
        ;;
   stop)
        killall x11vnc &
	killall Xvfb &
	rm -rf /tmp/.X11-unix/X${DISPLAY}
	rm -rf /tmp/.X${DISPLAY}-lock
	echo "[done]"
        ;;

esac
exit 0

