;;; switch-buffer-functions-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from switch-buffer-functions.el

(defvar switch-buffer-functions nil "\
A list of functions to be called when the current buffer has been changed.
Each is passed two arguments, the previous buffer and the current buffer.")
(autoload 'switch-buffer-functions-run "switch-buffer-functions" "\
Run `switch-buffer-functions' if needed.

This function checks the result of `current-buffer', and run
`switch-buffer-functions' when it has been changed from
the last buffer.

This function should be hooked to `post-command-hook'.")
(add-hook 'post-command-hook 'switch-buffer-functions-run)
(register-definition-prefixes "switch-buffer-functions" '("switch-buffer-functions--last-buffer"))

;;; End of scraped data

(provide 'switch-buffer-functions-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; switch-buffer-functions-autoloads.el ends here
