#+TITLE: org-html5presentation.el
#+AUTHOR: Takumi kinjo
#+OPTIONS: ^:nil num:nil toc:t
#+PRETTIFY_CSS:     resources/styles/prettify.css
#+FONTS_CSS:        resources/styles/fonts.css
#+PRESENTATION_CSS: resources/styles/presentation.css
#+COMMON_CSS:       resources/styles/common.css
#+DEFAULT_CSS:      resources/styles/default.css
#+MOON_CSS:         resources/styles/moon.css
#+SAND_CSS:         resources/styles/sand.css
#+SEA_WAVE_CSS:     resources/styles/sea_wave.css
#+IE_LT_9_JS:       http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js
#+PRETTIFY_JS:      resources/js/prettify.js
#+UTILS_JS:         resources/js/utils.js
#+HTML_HEAD:        <link rel="stylesheet" href="resources/styles/mystyle.css" type="text/css" />
* WHAT'S THIS?

  This library implements a HTML5 Presentation back-end for Org
  generic exporter based on ox-html.el.

  http://kinjo.github.io/org-html5presentation.el/ is a demo page.
  Please use the latest version of Google Chrome.

  * See http://orgmode.org/ about Org-mode.

  * See http://slides.html5rocks.com about HTML5 Presentation.

  This has been tested on *Org-mode version 8.3beta(commit cff54cd)* and *GNU Emacs 24.4*.

  If you want to use this on Org 8.2.10, please checkout
  tagged version. (tagged with org-8.2.10)

* INSTALLATION

  1) First of all, make sure your Org-mode version.
     This library has been tested on 8.3beta.
     : M-x org-version

  3) Get org-html5presentation.el. For example,
    : git clone https://github.com/kinjo/org-html5presentation.el.git \
    : ~/org-html5presentation.el

  4) Add load-path in your init.el and restart the emacs.
    : (add-to-list 'load-path "~/org-html5presentation.el")
    : (require 'ox-html5presentation)

* USAGE

  1. Open this README.org in your emacs.

  2. Type C-c C-e to convert Org file to an HTML5 Presentation file.

  3. `*Org Export Dispatcher*' buffer will open, so follow the menu.

  4. For example, if you type `p' and then `p', README.html will be generated.

  5. Finally, Open the generated file in your Google Chrome.

* PROPERTIES for CSS

  Following PROPERTIES are available for CSSs.

  * PRETTIFY_CSS : resources/styles/prettify.css is default. org-html5presentation-prettify-css defines.
  * FONTS_CSS : resources/styles/fonts.css is default. org-html5presentation-fonts-css defines.
  * PRESENTATION_CSS : resources/styles/presentation.css is default. org-html5presentation-presentation-css defines.
  * COMMON_CSS : resources/styles/common.css is default. org-html5presentation-common-css defines.
  * DEFAULT_CSS : resources/styles/default.css is default. org-html5presentation-default-css defines.
  * MOON_CSS : resources/styles/moon.css is default. org-html5presentation-moon-css defines.
  * SAND_CSS : resources/styles/sand.css is default. org-html5presentation-sand-css defines.
  * SEA_WAVE_CSS : css resources/styles/sea_wave.css is default. org-html5presentation-sea-wave-css defines.

* PROPERTIES for JS

  * IE_LT_9_JS : http://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js is default. org-html5presentation-ie-lt-9-js defines.
  * PRETTIFY_JS : resources/js/prettify.js is default. org-html5presentation-prettify-js defines.
  * UTILS_JS : resources/js/utils.js is default. org-html5presentation-utils-js defines.

* LICENSE

  Licensed under the GPLv3 license.
