#
# Available repositories are listed here:
# https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
#

language: cpp
sudo: required

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - python3-pip
            - libcppunit-dev

git:
  depth: 3

matrix:
    include:
        - os: linux
          compiler: g++
          dist: trusty
          env: T=g++-linux COMPILER_VERSION=-4.9
        - os: osx
          compiler: clang
          env: T=clang-osx

branches:
    only:
        - master
        - develop

script: ./scripts/travis.sh
