;;; move-text-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from move-text.el

(autoload 'move-text--total-lines "move-text" "\
Convenience function to get the total lines in the buffer / or narrowed buffer.")
(autoload 'move-text--at-first-line-p "move-text" "\
Predicate, is the point at the first line?")
(autoload 'move-text--at-penultimate-line-p "move-text" "\
Predicate, is the point at the penultimate line?")
(autoload 'move-text--last-line-is-just-newline "move-text" "\
Predicate, is last line just a newline?")
(autoload 'move-text--at-last-line-p "move-text" "\
Predicate, is the point at the last line?")
(autoload 'move-text-line-up "move-text" "\
Move the current line up." t)
(autoload 'move-text-line-down "move-text" "\
Move the current line down." t)
(autoload 'move-text-region "move-text" "\
Move the current region (START END) up or down by N lines.

(fn START END N)" t)
(autoload 'move-text-region-up "move-text" "\
Move the current region (START END) up by N lines.

(fn START END N)" t)
(autoload 'move-text-region-down "move-text" "\
Move the current region (START END) down by N lines.

(fn START END N)" t)
(autoload 'move-text-up "move-text" "\
Move the line or region (START END) up by N lines.

(fn START END N)" t)
(autoload 'move-text-down "move-text" "\
Move the line or region (START END) down by N lines.

(fn START END N)" t)
(autoload 'move-text-default-bindings "move-text" "\
Bind `move-text-up' and `move-text-down' to M-up & M-down." t)
(register-definition-prefixes "move-text" '("move-text-get-region-and-prefix"))

;;; End of scraped data

(provide 'move-text-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; move-text-autoloads.el ends here
