;;; ac-html-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ac-haml.el

(register-definition-prefixes "ac-haml" '("ac-haml-"))


;;; Generated autoloads from ac-html.el

(register-definition-prefixes "ac-html" '("ac-html-"))


;;; Generated autoloads from ac-html-core.el

(autoload 'ac-html-define-data-provider "ac-html-core" "\
Define ac-html data provider with this macro.
This macro is buggy and cannot be used now.

(fn PROVIDER &rest PAIRS)" nil t)
(function-put 'ac-html-define-data-provider 'lisp-indent-function 1)
(autoload 'ac-html-enable-data-provider "ac-html-core" "\
Enable data provider PROVIDER.

(fn PROVIDER)")
(autoload 'ac-html-define-ac-source "ac-html-core" "\
Define ac-html lang with this macro.

(fn LANG &rest PAIRS)" nil t)
(function-put 'ac-html-define-ac-source 'lisp-indent-function 1)
(register-definition-prefixes "ac-html-core" '("ac-html-"))


;;; Generated autoloads from ac-html-default-data-provider.el

(register-definition-prefixes "ac-html-default-data-provider" '("ac-html-" "web-completion-data-"))


;;; Generated autoloads from ac-html-testing-data-provider.el

(register-definition-prefixes "ac-html-testing-data-provider" '("ac-html-testing-"))


;;; Generated autoloads from ac-jade.el

(register-definition-prefixes "ac-jade" '("ac-jade-"))


;;; Generated autoloads from ac-slim.el

(register-definition-prefixes "ac-slim" '("ac-slim-"))

;;; End of scraped data

(provide 'ac-html-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ac-html-autoloads.el ends here
