;;; ox-clip-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ox-clip.el

(autoload 'ox-clip-get-command "ox-clip" "\
Get the command form OPTIONS.
OPTIONS is one of `ox-clip-w32-cmd', `ox-clip-osx-cmd', or
`ox-clip-linux-cmd'. Those may be a string, or a list of
candidates to choose from.

(fn OPTIONS)")
(autoload 'ox-clip-formatted-copy "ox-clip" "\
Export the selected region to HTML and copy it to the clipboard.
R1 and R2 define the selected region.

If SUBTREEP (interactively, the prefix argument) is non-nil then
export the current `org-mode' subtree, including hidden content.

(fn R1 R2 &optional SUBTREEP)" t)
(autoload 'ox-clip-image-to-clipboard "ox-clip" "\
Copy the image file or latex fragment at point to the clipboard as an image.
SCALE is a numerical
prefix (default=`ox-clip-default-latex-scale') that determines
the size of the latex image. It has no effect on other kinds of
images. Currently only works on Linux.

(fn &optional SCALE)" t)
(register-definition-prefixes "ox-clip" '("ox-clip-"))

;;; End of scraped data

(provide 'ox-clip-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ox-clip-autoloads.el ends here
