;;; charmap-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from charmap.el

(autoload 'charmap "charmap" "\
Display a specified unicode block." t)
(autoload 'charmap-all "charmap" "\
Display entire unicode table." t)
(register-definition-prefixes "charmap" '("charmap-" "with-charmap-buffer"))

;;; End of scraped data

(provide 'charmap-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; charmap-autoloads.el ends here
