#!/bin/sh
### BEGIN INIT INFO
# Provides:          vncserver
# Required-Start:    networking
# Default-Start:     3 4 5
# Default-Stop:      0 6
### END INIT INFO
PATH="$PATH:/usr/X11R6/bin/"

# The Username:Group that will run VNC
export USER="abelardo"
HOME="/home/$USER"

#${RUNAS}

# The display that VNC will use
DISPLAY="99"

# Color depth (between 8 and 32)
DEPTH=16

# The Desktop geometry to use.
#GEOMETRY="<WIDTH>x<HEIGHT>"
GEOMETRY="1900x1280"
OPTIONS="-SecurityTypes=VncAuth -auth /home/${USER}/.Xauthority -depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"

case "$1" in
start)
echo "Starting vncserver for user '${USER}' on localhost:${DISPLAY}"
su $USER -c "/usr/bin/vncserver ${OPTIONS}"
e=$?
if [ $e -eq 1 ]; then
  echo "Server is already running."
  return
fi

if [ $e -eq 255 ]; then
  echo "Server couldn't start."
  exit 1
fi
echo "[done]"
;;

stop)
echo "Stoping vncserver for user '${USER}' on localhost:${DISPLAY}"
su ${USER} -c "/usr/bin/vncserver -kill :${DISPLAY}"
rm -rf /tmp/.X11-unix/X2
rm -rf /tmp/.X2-lock
echo "[done]"
;;

restart)
$0 stop
$0 start
;;
esac

exit 0
