#!/bin/sh
### BEGIN INIT INFO
# Provides:          vncserver
# Required-Start:    networking
# Default-Start:     3 4 5
# Default-Stop:      0 6
### END INIT INFO
PATH="$PATH:/usr/X11R6/bin/"
PIDFILE=/var/run/vncserver.pid

# The Username:Group that will run VNC
export USER="abelardo"
HOME="/home/$USER"

#${RUNAS}

# The display that VNC will use
DISPLAY="2"

# Color depth (between 8 and 32)
DEPTH=16

# The Desktop geometry to use.
#GEOMETRY="<WIDTH>x<HEIGHT>"
GEOMETRY="1900x1280"
OPTIONS=" -depth ${DEPTH} -geometry ${GEOMETRY} :${DISPLAY}"

. /lib/lsb/init-functions

case "$1" in
start)
echo "Starting vncserver for user '${USER}' on localhost:${DISPLAY}"
start-stop-daemon --chuid $USER:$USER --start --pidfile $PIFILE --make-pidfile --exec /usr/bin/tightvncserver -- $OPTIONS
e=$?
if [ $e -eq 1 ]; then
  echo "Server is already running."
  return
fi

if [ $e -eq 255 ]; then
  echo "Server couldn't start."
  exit 1
fi
echo "[done]"
;;

stop)
echo "Stoping vncserver for user '${USER}' on localhost:${DISPLAY}"
su ${USER} -c "/usr/bin/tightvncserver -kill :${DISPLAY}"
rm -rf /tmp/.X11-unix/X2
start-stop-daemon -Kq -R 10 -p $PIDFILE
echo "[done]"
;;

restart)
$0 stop
$0 start
;;
esac

exit 0
