;;; flucui-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flucui-dark-theme.el

(register-definition-prefixes "flucui-dark-theme" '("flucui-dark"))


;;; Generated autoloads from flucui-light-theme.el

(register-definition-prefixes "flucui-light-theme" '("flucui-light"))


;;; Generated autoloads from flucui-themes.el

(add-to-list 'custom-theme-load-path (file-name-directory load-file-name))
(autoload 'flucui-themes-load-style "flucui-themes" "\
Load FlucUI theme variant STYLE.

Argument STYLE can be either 'light or 'dark.

(fn STYLE)" t)
(autoload 'flucui-themes-switch-style "flucui-themes" "\
Toggle between the light and dark style of FlucUI theme." t)
(register-definition-prefixes "flucui-themes" '("flucui-themes-current-style"))

;;; End of scraped data

(provide 'flucui-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flucui-themes-autoloads.el ends here
